import path from 'node:path';import {createHash} from 'node:crypto';import {pathToFileURL} from 'node:url';
import {markupTokens,markupAttributes} from './preview-markup.mjs';import {readUtf8Limited,readBufferLimited,writeBufferWithin} from './safe-files.mjs';
const escape=value=>String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const decode=value=>value.replace(/&(?:amp|quot|apos|lt|gt|#(\d+)|#x([\da-f]+));/gi,(all,decimal,hex)=>decimal?String.fromCodePoint(+decimal):hex?String.fromCodePoint(parseInt(hex,16)):({'&amp;':'&','&quot;':'"','&apos;':"'",'&lt;':'<','&gt;':'>'}[all.toLowerCase()]||all));
function cssDecode(value){return value.replace(/\\([\da-f]{1,6})\s?|\\([^\r\n])/gi,(_all,hex,char)=>hex?String.fromCodePoint(parseInt(hex,16)||0xfffd):char);}
/** CSS lexical reader: comments/strings are atomic; identifiers decode CSS escapes. */
function identifier(source,start){let i=start,value='';while(i<source.length){const ch=source[i];if(/[\w-]/.test(ch)){value+=ch;i++;}else if(ch==='\\'){const match=/^\\(?:[\da-f]{1,6}\s?|[^\r\n])/i.exec(source.slice(i));if(!match)break;value+=cssDecode(match[0]);i+=match[0].length;}else break;}return {value:value.toLowerCase(),end:i};}
function quoted(source,start){const quote=source[start];let i=start+1,value='';for(;i<source.length;i++){if(source[i]==='\\'){value+=source[i]+(source[++i]||'');}else if(source[i]===quote)return {value:cssDecode(value),end:i+1};else value+=source[i];}return {value:cssDecode(value),end:i};}
function urlValue(source,start){let i=start+1;while(/\s/.test(source[i]||'')&&i<source.length)i++;let value='';if(source[i]==='"'||source[i]==="'"){const token=quoted(source,i);value=token.value;i=token.end;}else{for(;i<source.length&&source[i]!==')';i++){if(source[i]==='\\'){value+=source[i]+(source[++i]||'');}else value+=source[i];}value=cssDecode(value.trim());}while(i<source.length&&source[i]!==')')i++;return {value,end:Math.min(i+1,source.length)};}
async function pack(root,manifest,cssDataUri){
 const assets={},documents={},diagnostics=[],cache=new Map();const unresolved=()=>{diagnostics.push({code:'ASSET_UNRESOLVED',message:'資源無法安全內嵌，已停用該引用'});return 'data:,';};
 const resolve=(url,base)=>{const decoded=decode(url).split(/[?#]/)[0];if(!decoded||/^(?:[a-z][\w+.-]*:|\/|\\)/i.test(decoded))throw Error('Non-local asset');return path.resolve(path.dirname(base),decodeURIComponent(decoded));};
 const asset=async(url,base)=>{if(url.startsWith('data:'))return url;try{const file=resolve(url,base),mime=({'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp','.avif':'image/avif','.svg':'image/svg+xml','.woff':'font/woff','.woff2':'font/woff2','.ttf':'font/ttf','.otf':'font/otf'})[path.extname(file).toLowerCase()];if(!mime)return unresolved();const bytes=await readBufferLimited(root,file),hash=createHash('sha256').update(mime).update(bytes).digest('hex');assets[hash]=`data:${mime};base64,${bytes.toString('base64')}`;return `st-asset-sha256:${hash}`;}catch{return unresolved();}};
 const cssAsset=source=>{const bytes=Buffer.from(source),hash=createHash('sha256').update('text/css').update(bytes).digest('hex');assets[hash]='data:text/css;base64,'+bytes.toString('base64');return `st-asset-sha256:${hash}`;};
 const stylesheet=source=>cssDataUri?`<link rel="stylesheet" href="${cssAsset(source)}">`:'<style>'+source+'</style>';
 const css=async(source,base,seen=new Set())=>{let result='',i=0;while(i<source.length){if(source.startsWith('/*',i)){const end=source.indexOf('*/',i+2);const j=end<0?source.length:end+2;result+=source.slice(i,j);i=j;continue;}if(source[i]==='"'||source[i]==="'"){const token=quoted(source,i);result+=source.slice(i,token.end);i=token.end;continue;}const start=i,isAt=source[i]==='@',token=identifier(source,isAt?i+1:i);if(token.end>(isAt?i+1:i)){let j=token.end;while(/\s/.test(source[j]||'')&&j<source.length)j++;if(isAt&&token.value==='import'){let value;if(source[j]==='"'||source[j]==="'"){value=quoted(source,j);j=value.end;}else{const keyword=identifier(source,j);j=keyword.end;while(/\s/.test(source[j]||'')&&j<source.length)j++;if(keyword.value==='url'&&source[j]==='('){value=urlValue(source,j);j=value.end;}}let tail='',depth=0;while(j<source.length){if(source[j]===';'&&depth===0)break;if(source[j]===String.fromCharCode(34)||source[j]===String.fromCharCode(39)){const quotedTail=quoted(source,j);tail+=source.slice(j,quotedTail.end);j=quotedTail.end;continue;}if(source.startsWith('/*',j)){const end=source.indexOf('*/',j+2),next=end<0?source.length:end+2;tail+=source.slice(j,next);j=next;continue;}if(source[j]==='(')depth++;if(source[j]===')')depth--;tail+=source[j++];}if(value){try{const file=resolve(value.value,base);if(seen.has(file))throw Error('CSS import cycle');const next=new Set(seen);next.add(file);const nested=await css(await readUtf8Limited(root,file),file,next);result+=cssDataUri?`@import url("${cssAsset(nested)}")${tail};`:tail.trim()?`@media ${tail.trim()}{${nested}}`:nested;}catch{unresolved();}}else unresolved();i=Math.min(j+1,source.length);continue;}if(!isAt&&token.value==='url'&&source[j]==='('){const value=urlValue(source,j);result+=`url("${await asset(value.value,base)}")`;i=value.end;continue;}result+=source.slice(start,token.end);i=token.end;continue;}result+=source[i++];}return result.replace(/<\/style/gi,'<\\/style');};
 for(const [id,relative]of Object.entries(manifest).sort(([a],[b])=>a<b?-1:a>b?1:0)){const file=path.resolve(root,relative);const source=await readUtf8Limited(root,file);if(cache.has(file)){documents[id]=cache.get(file);continue;}const output=[];
  for(const token of markupTokens(source)){if(!token.name){if(/^<\s*script\b/i.test(token.text))continue;if(/^<\s*style\b/i.test(token.text)){const start=token.text.indexOf('>')+1,end=token.text.toLowerCase().lastIndexOf('</style');output.push(stylesheet(await css(token.text.slice(start,end<0?undefined:end),file)));}else output.push(token.text);continue;}
   const name=token.name;if(['script','base','iframe','object','embed'].includes(name))continue;if(token.closing){output.push(`</${name}>`);continue;}
   const attrs=markupAttributes(token.text);delete attrs['data-st-expansion-anchor'];if(name==='meta'&&attrs['http-equiv'])continue;
   if(name==='link'){if(attrs.rel?.toLowerCase()==='stylesheet'&&attrs.href){try{const target=resolve(attrs.href,file);output.push(stylesheet(await css(await readUtf8Limited(root,target),target,new Set([target]))));}catch{unresolved();}}continue;}
   for(const key of Object.keys(attrs)){if(key.startsWith('on')||['srcdoc','srcset','action','formaction','ping','target','href','xlink:href','background'].includes(key))delete attrs[key];}
   if(attrs.style)attrs.style=await css(decode(attrs.style),file);if(attrs.src){if(['img','source','video','audio','input'].includes(name))attrs.src=await asset(decode(attrs.src),file);else delete attrs.src;}if(attrs.poster)attrs.poster=await asset(decode(attrs.poster),file);
   output.push(`<${name}${Object.entries(attrs).map(([key,value])=>` ${key}="${escape(decode(value))}"`).join('')}${token.selfClosing?'/':''}>`);
  }
  documents[id]=output.join('');cache.set(file,documents[id]);
 }
 return {schemaVersion:'2.2',documents,assets:Object.fromEntries(Object.entries(assets).sort(([a],[b])=>a<b?-1:a>b?1:0)),diagnostics};
}
// Historical inline-CSS fixture entry only; formal CLI uses packStandaloneDocuments.
/** @deprecated Preserve the pre-E fixture contract; retire with historical capture fixtures. */
export function packDocuments(root,manifest){return pack(root,manifest,false);}
export function packStandaloneDocuments(root,manifest){return pack(root,manifest,true);}
if(process.argv[1]&&pathToFileURL(path.resolve(process.argv[1])).href===import.meta.url){const root=path.resolve(process.argv[2]);const manifest=JSON.parse(await readUtf8Limited(root,path.join(root,'static-preview/manifest.json')));const packed=await packStandaloneDocuments(root,manifest);await writeBufferWithin(root,path.join(root,'viewer-documents.json'),JSON.stringify(packed));}
