import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import test from 'node:test';
import {chromium} from 'playwright';
import {pathToFileURL} from 'node:url';
const driver=path.resolve('screentrace-capture/capture-static-jsp.mjs');
async function fixture(version='2.2') {
 const root=await mkdtemp(path.join(os.tmpdir(),'preview-v2-')),output=path.join(root,'analysis'),web=path.join(root,'src/main/webapp');
 await mkdir(web,{recursive:true});await mkdir(output);
 const source={file:'src/main/webapp/page.jsp',line:1},proof=[{source,parser:'FixtureParser',resolution:'CONFIRMED'}];
 const graph={schemaVersion:version,application:{name:'fixture',path:'.',technologies:['JSP']},nodes:[{id:'screen',type:'SCREEN',name:'page',attributes:{view:source.file},source,confidence:'CONFIRMED',evidence:proof},{id:'email',type:'COMPONENT',name:'Email',attributes:{kind:'TEXT_INPUT',tag:'input',name:'email'},source,confidence:'CONFIRMED',evidence:proof}],relationships:[{id:'contains',type:'CONTAINS',from:'screen',to:'email',source,confidence:'CONFIRMED',evidence:proof}],behaviors:[],validationRules:[]};
 await writeFile(path.join(output,'application-graph.json'),JSON.stringify(graph));
 await writeFile(path.join(web,'page.jsp'),`<!doctype html><html><head><style>.same{color:rgb(11,22,33);padding:3px} .hidden{display:none}</style><script>globalThis.targetProbe='EXECUTED'</script></head><body><div class='same'>${'text'.repeat(25)}</div><div class='same'>Other</div><form><input name='email'></form><c:if test="\${allowed}"><span id='if'>\${name}</span></c:if><c:choose><c:when test="\${first}"><p id='one'>One</p></c:when><c:otherwise><p id='two'>Two</p></c:otherwise></c:choose><i class='hidden'>Hidden</i></body></html>`);
 return {root,output};
}
async function run(f,args=[]){const child=spawn(process.execPath,[driver,f.root,f.output,'--preview-v2',...args]);let error='';child.stderr.on('data',b=>error+=b);child.stdout.on('data',()=>{});const status=await new Promise(resolve=>child.on('close',resolve));return {status,error};}
async function read(f){return JSON.parse(await readFile(path.join(f.output,'static-preview/element-styles.json'),'utf8'));}
test('captures every element with stable paths, all computed deltas and lossless style roundtrip',async()=>{
 const f=await fixture();let browser;
 try{const result=await run(f);assert.equal(result.status,0,result.error);const capture=await read(f),screen=capture.screens.screen;
 assert.equal(capture.version,'2');assert.equal(capture.schemaVersion,'2.2');assert.deepEqual(screen.elements.map(e=>e.tag),['html','body','div','div','form','input','span','p','p','i']);
 assert.equal(screen.elements[2].path,'body>div[1]');assert.equal(screen.elements[3].path,'body>div[2]');assert.equal(screen.elements[2].text.length,80);assert.equal(screen.elements[2].styleId,screen.elements[3].styleId);
 assert.equal(screen.elements.find(e=>e.tag==='input').graphComponentId,'email');assert.equal(screen.elements.find(e=>e.tag==='i').graphComponentId,null);assert.equal(screen.elements.find(e=>e.tag==='i').bounds.width,0);
 assert.equal(screen.rendering.mode,'reconstructed');assert.ok(screen.dynamicExpressions.includes('${name}'));assert.ok(screen.dynamicExpressions.includes('${allowed}'));
 assert.ok(screen.elements.find(e=>e.id==='if').conditions.includes('${allowed}'));assert.ok(screen.elements.find(e=>e.id==='one').conditions.includes('${first}'));assert.ok(screen.elements.find(e=>e.id==='two').conditions.some(c=>c.includes('${first}')));
 const html=await readFile(path.join(f.output,'static-preview/screen.html'),'utf8');assert.match(html,/data-st-conditional/);assert.doesNotMatch(html,/<script\b/i);
 browser=await chromium.launch();const context=await browser.newContext({viewport:{width:1440,height:900},javaScriptEnabled:false});const page=await context.newPage();await page.goto(pathToFileURL(path.join(f.output,'static-preview/screen.html')).href);
 const originals=await page.locator('html,body,body *').evaluateAll(nodes=>nodes.filter(n=>!['SCRIPT','STYLE'].includes(n.tagName)).map(n=>Object.fromEntries([...getComputedStyle(n)].sort().map(k=>[k,getComputedStyle(n).getPropertyValue(k)]))));
 assert.equal(originals.length,screen.elements.length);for(let i=0;i<originals.length;i++){const e=screen.elements[i];assert.deepEqual({...capture.defaults[e.defaultId],...capture.styles[e.styleId]},originals[i]);for(const [k,v] of Object.entries(capture.styles[e.styleId]))assert.notEqual(v,capture.defaults[e.defaultId][k]);}
 const png=Buffer.from(screen.thumbnail.split(',')[1],'base64');assert.match(screen.thumbnail,/^data:image\/png;base64,/);assert.ok(png.readUInt32BE(16)<=320);assert.ok(png.readUInt32BE(20)>0);
 const again=await run(f);assert.equal(again.status,0,again.error);assert.deepEqual(await read(f),capture);
 }finally{await browser?.close();await rm(f.root,{recursive:true,force:true});}
});
test('limits diagnose overflow without dropping any element or style',async()=>{const f=await fixture();try{const result=await run(f,['--style-element-limit=2','--style-byte-limit=1']);assert.equal(result.status,0,result.error);const c=await read(f);assert.equal(c.screens.screen.elements.length,10);assert.ok(c.diagnostics.some(d=>d.code==='STYLE_ELEMENT_LIMIT'));assert.ok(c.diagnostics.some(d=>d.code==='STYLE_BYTE_LIMIT'));assert.equal(c.screens.screen.rendering.mode,'reconstructed');}finally{await rm(f.root,{recursive:true,force:true});}});
test('new capture explicitly rejects historical graphs',async()=>{const f=await fixture('2.1');try{const result=await run(f);assert.notEqual(result.status,0);assert.match(result.error,/2\.2.*2\.1|2\.1.*2\.2/);}finally{await rm(f.root,{recursive:true,force:true});}});
test('HTML screens and declared local tag libraries preserve all branch/source evidence without executing target scripts',async()=>{
 const f=await fixture();try{
 const web=path.join(f.root,'src/main/webapp');await mkdir(path.join(web,'WEB-INF/tags'),{recursive:true});
 await writeFile(path.join(web,'WEB-INF/tags/card.tag'),'<%@ tag body-content="scriptless" %>\n<c:if test="${showCard}"><b id="card">${cardName}</b></c:if><jsp:doBody/>');
 await writeFile(path.join(web,'piece.jsp'),'<small id="included">Piece</small>');
 await writeFile(path.join(web,'page.html'),'<%@ taglib prefix="ui" tagdir="/WEB-INF/tags" %><html><head></head><body><ui:card><em>Body</em></ui:card><jsp:include page="piece.jsp"/><script>fetch("https://example.invalid/probe")</script><html:text property="email"/></body></html>');
 const graph=JSON.parse(await readFile(path.join(f.output,'application-graph.json'),'utf8'));graph.nodes[0].attributes.view='src/main/webapp/page.html';await writeFile(path.join(f.output,'application-graph.json'),JSON.stringify(graph));
 const result=await run(f);assert.equal(result.status,0,result.error);const c=await read(f),s=c.screens.screen;
 assert.equal(s.rendering.mode,'reconstructed');assert.ok(s.elements.some(e=>e.id==='card'&&e.conditions.includes('${showCard}')&&e.source.file==='src/main/webapp/WEB-INF/tags/card.tag'&&e.source.line===2));
 assert.ok(s.elements.some(e=>e.tag==='em'&&e.text==='Body'));assert.ok(s.elements.some(e=>e.id==='included'&&e.source.file==='src/main/webapp/piece.jsp'));
 assert.ok(s.dynamicExpressions.includes('${cardName}'));assert.ok(s.dynamicExpressions.includes('${showCard}'));assert.equal(s.elements.find(e=>e.tag==='input').graphComponentId,'email');
 const html=await readFile(path.join(f.output,'static-preview/screen.html'),'utf8');assert.doesNotMatch(html,/<script\b/i);
 }finally{await rm(f.root,{recursive:true,force:true});}
});
test('source order maps anonymous elements and ambiguous matches retain all candidates for every occurrence',async()=>{
 const f=await fixture();try{
 const file='src/main/webapp/page.jsp';await writeFile(path.join(f.root,file),'<html><body>\n<button>First</button>\n<button>Second</button>\n<input name="shared"><input name="shared">\n</body></html>');
 const graph=JSON.parse(await readFile(path.join(f.output,'application-graph.json'),'utf8'));graph.nodes=graph.nodes.slice(0,1);graph.relationships=[];
 for(const [id,line,tag,name] of [['second',3,'button'],['first',2,'button'],['shared-a',4,'input','shared'],['shared-b',4,'input','shared']]){const source={file,line};graph.nodes.push({id,type:'COMPONENT',name:id,attributes:{kind:tag==='button'?'BUTTON':'TEXT_INPUT',tag,...(name?{name}:{})},source,confidence:'CONFIRMED',evidence:[{source,parser:'FixtureParser',resolution:'CONFIRMED'}]});graph.relationships.push({id:'contains-'+id,type:'CONTAINS',from:'screen',to:id,source,confidence:'CONFIRMED',evidence:[{source,parser:'FixtureParser',resolution:'CONFIRMED'}]});}
 await writeFile(path.join(f.output,'application-graph.json'),JSON.stringify(graph));const result=await run(f);assert.equal(result.status,0,result.error);const elements=(await read(f)).screens.screen.elements;
 assert.deepEqual(elements.filter(e=>e.tag==='button').map(e=>e.graphComponentId),['first','second']);
 for(const element of elements.filter(e=>e.tag==='input')){assert.equal(element.graphComponentId,null);assert.equal(element.componentResolution,'AMBIGUOUS');assert.deepEqual(element.graphComponentCandidates,['shared-a','shared-b']);}
 }finally{await rm(f.root,{recursive:true,force:true});}
});
test('new reconstruction never triggers script/event/network side-effect probes',async()=>{
 const {createServer}=await import('node:http'),{once}=await import('node:events');let probes=0;const server=createServer((_request,response)=>{probes++;response.end('probe');});server.listen(0,'127.0.0.1');await once(server,'listening');const f=await fixture();try{const url=`http://127.0.0.1:${server.address().port}`;await writeFile(path.join(f.root,'src/main/webapp/page.jsp'),`<html><head><script>fetch('${url}/script')</script><script src="${url}/external.js"></script><style>@import url('${url}/import.css')</style></head><body onload="fetch('${url}/event')"><img src="${url}/pixel" onerror="fetch('${url}/error')"><button>Safe</button></body></html>`);const result=await run(f);assert.equal(result.status,0,result.error);assert.equal(probes,0);assert.equal((await read(f)).screens.screen.rendering.mode,'reconstructed');const html=await readFile(path.join(f.output,'static-preview/screen.html'),'utf8');assert.doesNotMatch(html,/<script\b|onload=|onerror=/i);assert.match(html,/script-src 'none'/);}finally{server.close();await rm(f.root,{recursive:true,force:true});}
});
test('CSS animation capture is deterministic across repeated reconstruction',async()=>{const f=await fixture();try{await writeFile(path.join(f.root,'src/main/webapp/page.jsp'),'<html><head><style>@keyframes drift{from{color:rgb(0,0,0);transform:translateX(0px)}to{color:rgb(255,0,0);transform:translateX(100px)}}div{animation:drift 1s infinite linear}</style></head><body><div>Animated</div></body></html>');assert.equal((await run(f)).status,0);const first=await read(f);assert.equal((await run(f)).status,0);assert.deepEqual(await read(f),first);}finally{await rm(f.root,{recursive:true,force:true});}});
test('same-line anonymous ambiguity does not consume candidates for the next occurrence',async()=>{const f=await fixture();try{const file='src/main/webapp/page.jsp';await writeFile(path.join(f.root,file),'<html><body>\n<button>One</button><button>Two</button></body></html>');const graph=JSON.parse(await readFile(path.join(f.output,'application-graph.json'),'utf8'));graph.nodes=graph.nodes.slice(0,1);graph.relationships=[];for(const id of ['a','b']){const source={file,line:2};graph.nodes.push({id,type:'COMPONENT',name:id,attributes:{tag:'button',kind:'BUTTON'},source,confidence:'CONFIRMED',evidence:[{source,parser:'FixtureParser',resolution:'CONFIRMED'}]});graph.relationships.push({id:'contains-'+id,type:'CONTAINS',from:'screen',to:id,source,confidence:'CONFIRMED',evidence:[{source,parser:'FixtureParser',resolution:'CONFIRMED'}]});}await writeFile(path.join(f.output,'application-graph.json'),JSON.stringify(graph));assert.equal((await run(f)).status,0);const items=(await read(f)).screens.screen.elements.filter(e=>e.tag==='button');assert.equal(items.length,2);for(const item of items){assert.equal(item.componentResolution,'AMBIGUOUS');assert.deepEqual(item.graphComponentCandidates,['a','b']);assert.equal(item.graphComponentId,null);}}finally{await rm(f.root,{recursive:true,force:true});}});
test('canonical occurrence IDs map same-line anonymous components in original source order',async()=>{const f=await fixture();try{const file='src/main/webapp/page.jsp';await writeFile(path.join(f.root,file),'<html><body>\n<button>One</button><button>Two</button></body></html>');const ids=['component:2d116442-a28f-3d32-a3ee-f8bbda23761a','component:8071bf7b-683b-3bc2-963d-d56278f5f19e'];const graph=JSON.parse(await readFile(path.join(f.output,'application-graph.json'),'utf8'));graph.nodes=graph.nodes.slice(0,1);graph.relationships=[];for(const id of [...ids].reverse()){const source={file,line:2};graph.nodes.push({id,type:'COMPONENT',name:id,attributes:{tag:'button',kind:'BUTTON'},source,confidence:'CONFIRMED',evidence:[{source,parser:'FixtureParser',resolution:'CONFIRMED'}]});graph.relationships.push({id:'contains-'+id,type:'CONTAINS',from:'screen',to:id,source,confidence:'CONFIRMED',evidence:[{source,parser:'FixtureParser',resolution:'CONFIRMED'}]});}await writeFile(path.join(f.output,'application-graph.json'),JSON.stringify(graph));assert.equal((await run(f)).status,0);const items=(await read(f)).screens.screen.elements.filter(e=>e.tag==='button');assert.deepEqual(items.map(e=>e.graphComponentId),ids);}finally{await rm(f.root,{recursive:true,force:true});}});
test('element text excludes head and raw script/style contents',async()=>{const f=await fixture();try{await writeFile(path.join(f.root,'src/main/webapp/page.jsp'),'<html><head><title>Secret title</title><style>.secret{color:red}</style></head><body><div><style>.other{color:blue}</style>Visible</div></body></html>');assert.equal((await run(f)).status,0);const elements=(await read(f)).screens.screen.elements;assert.deepEqual(elements.map(e=>e.tag),['html','body','div']);assert.deepEqual(elements.map(e=>e.text),['Visible','Visible','Visible']);}finally{await rm(f.root,{recursive:true,force:true});}});
