package io.screentrace.adapter.spring;
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.*;
import com.github.javaparser.ast.body.*;
import com.github.javaparser.ast.expr.*;
import com.github.javaparser.ast.nodeTypes.NodeWithAnnotations;
import io.screentrace.core.*;
import io.screentrace.core.ApplicationGraph.*;
import io.screentrace.scanner.ProjectScanner.ProjectInventory;
import io.screentrace.scanner.SafeProjectFiles;
import java.util.*;
import com.fasterxml.jackson.databind.ObjectMapper;

/** Server constraints from source declarations; no reflection, class loading or validation execution. */
final class SpringServerValidation {
 private record Type(String name,Node node,String file,CompilationUnit unit) { }
 private static final Set<String> CONSTRAINTS=Set.of("NotNull","NotBlank","NotEmpty","Null","AssertTrue","AssertFalse","Size","Length","Min","Max","DecimalMin","DecimalMax","Positive","PositiveOrZero","Negative","NegativeOrZero","Digits","Email","Pattern","Past","PastOrPresent","Future","FutureOrPresent");
 private final Map<String,List<Type>> types=new TreeMap<>();private final Map<String,ValidationRule> rules=new TreeMap<>();private final List<Diagnostic> diagnostics=new ArrayList<>();private final Map<String,GraphNode> nodes=new TreeMap<>();private ApplicationGraph graph;private List<AnalysisEvidence> activationProof=List.of();
 static ApplicationGraph enrich(ApplicationGraph graph,ProjectInventory inventory){return new SpringServerValidation().apply(graph,inventory);}
 private ApplicationGraph apply(ApplicationGraph graph,ProjectInventory inventory){this.graph=graph;graph.nodes().forEach(n->nodes.put(n.id(),n));graph.validationRules().forEach(r->rules.put(r.id(),r));diagnostics.addAll(graph.diagnostics());
  for(var file:inventory.javaFiles()){String relative=inventory.root().relativize(file).toString().replace('\\','/');try{var parsed=new JavaParser(new com.github.javaparser.ParserConfiguration().setLanguageLevel(com.github.javaparser.ParserConfiguration.LanguageLevel.JAVA_17)).parse(SafeProjectFiles.readUtf8Limited(inventory.root(),file,SafeProjectFiles.MAX_SOURCE_FILE_BYTES));if(!parsed.isSuccessful()){diagnostic(new SourceLocation(relative,1),"SERVER_VALIDATION_SOURCE","檢核來源無法解析");continue;}var unit=parsed.getResult().orElseThrow();for(var type:unit.findAll(ClassOrInterfaceDeclaration.class))addType(type.getFullyQualifiedName().orElse(type.getNameAsString()),type,relative,unit);for(var type:unit.findAll(RecordDeclaration.class))addType(type.getFullyQualifiedName().orElse(type.getNameAsString()),type,relative,unit);}catch(Exception error){diagnostic(new SourceLocation(relative,1),"SERVER_VALIDATION_SOURCE","檢核來源無法安全讀取");}}
  for(var endpoint:graph.nodes())if(endpoint.type()==NodeType.ENDPOINT){var handlers=graph.relationships().stream().filter(e->e.type()==EdgeType.HANDLED_BY&&e.from().equals(endpoint.id())).map(e->nodes.get(e.to())).filter(Objects::nonNull).toList();for(var handler:handlers){var candidates=types.values().stream().flatMap(Collection::stream).filter(t->t.file().equals(handler.source().file())&&t.node() instanceof ClassOrInterfaceDeclaration c&&c.getNameAsString().equals(handler.attributes().get("class"))).toList();for(var owner:candidates){var declaration=(ClassOrInterfaceDeclaration)owner.node();for(var method:declaration.getMethods())if(method.getNameAsString().equals(handler.attributes().get("method"))&&method.getBegin().map(p->p.line).orElse(1)==handler.source().line())process(endpoint,owner,method);}}}
  for(var node:new ArrayList<>(nodes.values()))if(node.type()==NodeType.ENDPOINT){List<String> ids=rules.values().stream().filter(r->r.parameters().getOrDefault("endpointIds","").contains(node.id())).map(ValidationRule::id).sorted().toList();if(!ids.isEmpty()){var attrs=new TreeMap<>(node.attributes());attrs.put("validationRuleIds",json(ids));nodes.put(node.id(),new GraphNode(node.id(),node.type(),node.name(),attrs,node.source(),node.confidence(),node.evidence()));}}
  return io.screentrace.parser.jsp.UrlGraphContribution.hidePrivateLocations(new ApplicationGraph(graph.application(),List.copyOf(nodes.values()),graph.relationships(),diagnostics.stream().distinct().toList(),graph.apiContracts(),graph.schemaVersion(),graph.behaviors(),List.copyOf(rules.values())));
 }
 private void addType(String name,Node node,String file,CompilationUnit unit){types.computeIfAbsent(name,k->new ArrayList<>()).add(new Type(name,node,file,unit));}
 private List<Type> resolve(String name,CompilationUnit unit){String bare=name.replaceAll("<.*>","").replace("[]","");if(types.containsKey(bare))return types.get(bare);String qualified=qualify(bare,unit);return types.getOrDefault(qualified,List.of());}
 private static String qualify(String name,CompilationUnit unit){if(name.contains("."))return name;for(var i:unit.getImports())if(!i.isAsterisk()&&!i.isStatic()&&i.getName().getIdentifier().equals(name))return i.getNameAsString();return unit.getPackageDeclaration().map(p->p.getNameAsString()+"."+name).orElse(name);}
 private static boolean annotation(AnnotationExpr a,CompilationUnit unit,String... expected){String name=a.getNameAsString();if(name.contains("."))return Arrays.asList(expected).contains(name);for(var i:unit.getImports())if(!i.isAsterisk()&&!i.isStatic()&&i.getName().getIdentifier().equals(name))return Arrays.asList(expected).contains(i.getNameAsString());for(String qualified:expected)if(qualified.endsWith("."+name)&&unit.getImports().stream().anyMatch(i->i.isAsterisk()&&!i.isStatic()&&qualified.equals(i.getNameAsString()+"."+name)))return true;return false;}
 private static boolean activated(NodeWithAnnotations<?> node,CompilationUnit unit){return node.getAnnotations().stream().anyMatch(a->annotation(a,unit,"javax.validation.Valid","jakarta.validation.Valid","org.springframework.validation.annotation.Validated"));}
 private static SourceLocation source(String file,Node node){return new SourceLocation(file,node.getBegin().map(p->p.line).orElse(1));}
 private void process(GraphNode endpoint,Type owner,MethodDeclaration method){for(var parameter:method.getParameters()){
   activationProof=List.of();
   if(activated(parameter,owner.unit())){activationProof=parameter.getAnnotations().stream().filter(a->annotation(a,owner.unit(),"javax.validation.Valid","jakarta.validation.Valid","org.springframework.validation.annotation.Validated")).map(a->new AnalysisEvidence(source(owner.file(),a),"SpringServerValidation",a.isSingleMemberAnnotationExpr()||a.isNormalAnnotationExpr()?ResolutionStatus.UNRESOLVED:ResolutionStatus.CONFIRMED,"Bean Validation 啟用："+a)).toList();var candidates=resolve(parameter.getTypeAsString(),owner.unit());if(candidates.size()==1)constraints(endpoint,candidates.get(0),"",new HashSet<>());else diagnostic(source(owner.file(),parameter),"SERVER_VALIDATION_TYPE","檢核型別無法唯一解析："+parameter.getTypeAsString());}
   if(activated(owner.node() instanceof ClassOrInterfaceDeclaration c?c:method,owner.unit())||activated(method,owner.unit()))for(var a:parameter.getAnnotations())constraint(endpoint,owner,parameter.getNameAsString(),a);
   for(var binder:((ClassOrInterfaceDeclaration)owner.node()).getMethods())if(binder.getAnnotations().stream().anyMatch(a->annotation(a,owner.unit(),"org.springframework.web.bind.annotation.InitBinder")))binder(endpoint,owner,binder,parameter);
  }}
 private void constraints(GraphNode endpoint,Type type,String prefix,Set<String> visited){if(!visited.add(type.name())){diagnostic(source(type.file(),type.node()),"SERVER_VALIDATION_CYCLE","巢狀檢核循環："+type.name());return;}
  if(type.node() instanceof ClassOrInterfaceDeclaration c){for(var parent:c.getExtendedTypes()){var candidates=resolve(parent.getNameAsString(),type.unit());if(candidates.size()==1)constraints(endpoint,candidates.get(0),prefix,new HashSet<>(visited));}
   for(var field:c.getFields())if(!field.isStatic())for(var variable:field.getVariables()){String name=prefix+variable.getNameAsString();for(var a:field.getAnnotations())constraint(endpoint,type,name,a);if(activated(field,type.unit()))cascade(endpoint,type,variable.getTypeAsString(),name,visited);}
   for(var method:c.getMethods())if(!method.isStatic()&&method.getParameters().isEmpty()&&method.getNameAsString().startsWith("get")&&method.getNameAsString().length()>3){String name=prefix+java.beans.Introspector.decapitalize(method.getNameAsString().substring(3));for(var a:method.getAnnotations())constraint(endpoint,type,name,a);if(activated(method,type.unit()))cascade(endpoint,type,method.getTypeAsString(),name,visited);}
  }else if(type.node() instanceof RecordDeclaration record)for(var parameter:record.getParameters()){String name=prefix+parameter.getNameAsString();for(var a:parameter.getAnnotations())constraint(endpoint,type,name,a);if(activated(parameter,type.unit()))cascade(endpoint,type,parameter.getTypeAsString(),name,visited);}
 }
 private void cascade(GraphNode endpoint,Type owner,String name,String field,Set<String> visited){var candidates=resolve(name,owner.unit());if(candidates.size()==1)constraints(endpoint,candidates.get(0),field+".",new HashSet<>(visited));else diagnostic(source(owner.file(),owner.node()),"SERVER_VALIDATION_TYPE","巢狀檢核型別未解析："+name);}
 private void constraint(GraphNode endpoint,Type type,String field,AnnotationExpr a){String name=a.getName().getIdentifier();if(!CONSTRAINTS.contains(name)||!annotation(a,type.unit(),"javax.validation.constraints."+name,"jakarta.validation.constraints."+name))return;Map<String,String> parameters=new TreeMap<>();if(a.isSingleMemberAnnotationExpr())parameters.put("value",literal(a.asSingleMemberAnnotationExpr().getMemberValue()));if(a.isNormalAnnotationExpr())for(var pair:a.asNormalAnnotationExpr().getPairs())parameters.put(pair.getNameAsString(),literal(pair.getValue()));String kind=switch(name){case "NotNull","NotBlank","NotEmpty"->"required";case "Size","Length"->"length";case "Min","Max","DecimalMin","DecimalMax","Positive","PositiveOrZero","Negative","NegativeOrZero","Digits"->"range";case "Email"->"email";case "Pattern"->"pattern";default->"custom";};parameters.put("constraint",name);emit(endpoint,type.file(),type.name()+":"+field,field,kind,a.toString(),a.isNormalAnnotationExpr()?a.asNormalAnnotationExpr().getPairs().stream().filter(p->p.getNameAsString().equals("message")&&p.getValue().isStringLiteralExpr()).map(p->p.getValue().asStringLiteralExpr().asString()).findFirst().orElse(null):null,parameters,List.of(new AnalysisEvidence(source(type.file(),a),"SpringServerValidation",parameters.containsKey("groups")?ResolutionStatus.UNRESOLVED:ResolutionStatus.CONFIRMED,"Bean Validation："+a)),parameters.containsKey("groups")?ResolutionStatus.UNRESOLVED:ResolutionStatus.CONFIRMED);}
 private static String literal(Expression expression){return expression.isStringLiteralExpr()?expression.asStringLiteralExpr().asString():expression.toString();}
 private void binder(GraphNode endpoint,Type owner,MethodDeclaration binder,Parameter parameter){String model=null;for(var a:parameter.getAnnotations())if(annotation(a,owner.unit(),"org.springframework.web.bind.annotation.ModelAttribute")){if(a.isSingleMemberAnnotationExpr()&&a.asSingleMemberAnnotationExpr().getMemberValue().isStringLiteralExpr())model=a.asSingleMemberAnnotationExpr().getMemberValue().asStringLiteralExpr().asString();}
  for(var a:binder.getAnnotations())if(annotation(a,owner.unit(),"org.springframework.web.bind.annotation.InitBinder")&&a.isSingleMemberAnnotationExpr()){var value=a.asSingleMemberAnnotationExpr().getMemberValue();if(!value.isStringLiteralExpr()||!value.asStringLiteralExpr().asString().equals(model))return;}
  for(var call:binder.findAll(MethodCallExpr.class))if(Set.of("addValidators","setValidator","replaceValidators").contains(call.getNameAsString()))for(var argument:call.getArguments()){
   if(!argument.isObjectCreationExpr()){diagnostic(source(owner.file(),call),"SERVER_VALIDATOR_UNRESOLVED","Validator 註冊無法靜態解析："+call);continue;}var candidates=resolve(argument.asObjectCreationExpr().getTypeAsString(),owner.unit());if(candidates.size()!=1||!(candidates.get(0).node() instanceof ClassOrInterfaceDeclaration validator)){diagnostic(source(owner.file(),call),"SERVER_VALIDATOR_UNRESOLVED","Validator 型別不唯一");continue;}var type=candidates.get(0);if(validator.getImplementedTypes().stream().noneMatch(t->qualify(t.getNameAsString(),type.unit()).equals("org.springframework.validation.Validator")||t.getNameAsString().equals("Validator")&&type.unit().getImports().stream().anyMatch(i->i.isAsterisk()&&i.getNameAsString().equals("org.springframework.validation"))))continue;
   var supports=validator.getMethodsByName("supports");List<String> supported=supports.stream().flatMap(m->m.findAll(ClassExpr.class).stream()).map(c->qualify(c.getTypeAsString(),type.unit())).distinct().toList();if(supported.size()!=1||!supported.get(0).equals(qualify(parameter.getTypeAsString(),owner.unit())))continue;
   for(var validate:validator.getMethodsByName("validate"))for(var reject:validate.findAll(MethodCallExpr.class))if(reject.getNameAsString().equals("rejectValue")&&reject.getArguments().size()>=2&&reject.getArgument(0).isStringLiteralExpr()){
    String field=reject.getArgument(0).asStringLiteralExpr().asString(),message=null;if(reject.getArguments().size()>=3&&reject.getArgument(reject.getArguments().size()-1).isStringLiteralExpr())message=reject.getArgument(reject.getArguments().size()-1).asStringLiteralExpr().asString();Map<String,String> parameters=new TreeMap<>();parameters.put("messageCode",literal(reject.getArgument(1)));reject.findAncestor(com.github.javaparser.ast.stmt.IfStmt.class).ifPresent(condition->parameters.put("condition",condition.getCondition().toString()));var confidence=call.findAncestor(com.github.javaparser.ast.stmt.IfStmt.class).isPresent()?ResolutionStatus.UNRESOLVED:ResolutionStatus.CONFIRMED;
    var proof=List.of(new AnalysisEvidence(source(owner.file(),binder),"SpringServerValidation",confidence,"Spring @InitBinder："+binder.getNameAsString()),new AnalysisEvidence(source(type.file(),reject),"SpringServerValidation",confidence,"Spring Validator："+reject));emit(endpoint,type.file(),type.name()+":"+field,field,"custom",reject.toString(),message,parameters,proof,confidence);
   }
  }
 }
 private void emit(GraphNode endpoint,String file,String key,String field,String kind,String expression,String message,Map<String,String> parameters,List<AnalysisEvidence> proof,ResolutionStatus confidence){String id=StableGraphIds.validation(file,key,kind,expression,0);TreeSet<String> fields=new TreeSet<>(List.of(field));Set<String> forms=new TreeSet<>();graph.relationships().stream().filter(e->e.type()==EdgeType.TRIGGERS&&e.to().equals(endpoint.id())).forEach(e->forms.add(e.from()));for(var n:graph.nodes())if(n.type()==NodeType.COMPONENT&&field.equals(n.attributes().get("field"))&&(forms.contains(n.id())||forms.contains(n.attributes().get("formId"))))fields.add(n.id());var old=rules.get(id);TreeSet<String> endpoints=new TreeSet<>();endpoints.add(endpoint.id());List<AnalysisEvidence> evidence=new ArrayList<>(proof);evidence.addAll(activationProof);if(old!=null){fields.addAll(old.fields());evidence.addAll(old.evidence());try{for(var value:new ObjectMapper().readTree(old.parameters().get("endpointIds")))endpoints.add(value.asText());}catch(Exception ignored){}}
  var params=new TreeMap<>(parameters);params.put("endpointIds",json(endpoints));rules.put(id,new ValidationRule(id,kind,List.copyOf(fields),message,ValidationLayer.SERVER,params,evidence.stream().distinct().sorted().toList()));
 }
 private static String json(Object value){try{return new ObjectMapper().writeValueAsString(value);}catch(Exception error){throw new IllegalStateException(error);}}
 private void diagnostic(SourceLocation source,String code,String message){diagnostics.add(new Diagnostic(message,Confidence.UNRESOLVED,source,code,List.of(new AnalysisEvidence(source,"SpringServerValidation",ResolutionStatus.UNRESOLVED,message))));}
}
