package io.screentrace.parser.jsp;
import static org.junit.jupiter.api.Assertions.*;
import io.screentrace.core.ApplicationGraph.*;
import io.screentrace.scanner.ProjectScanner;
import java.nio.file.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
class UrlResolutionTest {
 @TempDir Path root;
 UrlResolution.Endpoint endpoint(String id,String path,String method){return new UrlResolution.Endpoint(id,path,method,List.of());}
 UrlResolution.Context context(String... paths){return new UrlResolution.Context(Arrays.stream(paths).map(p->new UrlResolution.ContextValue(p,new SourceLocation("settings.json",1))).toList(),List.of());}
 @Test void exactNormalizesOnlyProvenContextAndRequestDecorations(){var r=UrlResolution.resolve("/shop/api;jsessionid=abc?q=1#part","GET",context("/shop"),List.of(endpoint("api","/api","GET")),false);assertEquals(Confidence.CONFIRMED,r.confidence());assertEquals(List.of("api"),r.candidates());assertEquals(List.of("/api"),r.paths());assertTrue(r.evidence().stream().anyMatch(e->e.source().file().equals("settings.json")));}
 @Test void templatesWildcardsAndExtensionMappingsAreInferred(){for(String pattern:List.of("/api/{id}","/api/*","/api/**")){assertEquals(Confidence.INFERRED,UrlResolution.resolve("/api/7","GET",context(""),List.of(endpoint("one",pattern,"GET")),false).confidence());}assertEquals(Confidence.INFERRED,UrlResolution.resolve("/save.do","POST",context(""),List.of(endpoint("save","/save","ANY")),List.of("*.do"),false).confidence());assertEquals(Confidence.INFERRED,UrlResolution.resolve("/save.action","GET",context(""),List.of(endpoint("save","/save","ANY")),List.of("*.action"),false).confidence());}
 @Test void everyCompatibleCandidateRemainsAmbiguous(){var r=UrlResolution.resolve("/api/7","GET",context(""),List.of(endpoint("z","/api/{id}","GET"),endpoint("a","/api/7","GET")),false);assertEquals(Confidence.AMBIGUOUS,r.confidence());assertEquals(List.of("a","z"),r.candidates());}
 @Test void methodMismatchNeverLinksAndMissingMethodMeansGet(){assertTrue(UrlResolution.resolve("/api","POST",context(""),List.of(endpoint("a","/api","GET")),false).diagnostics().contains("URL_METHOD_MISMATCH"));assertEquals(List.of(),UrlResolution.resolve("/api","POST",context(""),List.of(endpoint("a","/api","GET")),false).candidates());assertEquals(List.of("a"),UrlResolution.resolve("/api",null,context(""),List.of(endpoint("a","/api","GET")),false).candidates());}
 @Test void unknownContextIsNotInvented(){var r=UrlResolution.resolve("/shop/api","GET",context(),List.of(endpoint("api","/api","GET")),false);assertEquals(Confidence.UNRESOLVED,r.confidence());assertTrue(r.diagnostics().contains("CONTEXT_PATH_UNSPECIFIED"));assertEquals(List.of(),r.candidates());}
 @Test void standardExpressionNeedsActualContextUnknownVariablesNeverStrip(){assertEquals(List.of("api"),UrlResolution.resolve("{pageContext.request.contextPath}/api","GET",context("/shop"),List.of(endpoint("api","/api","GET")),true).candidates());assertEquals(Confidence.UNRESOLVED,UrlResolution.resolve("{ctx}/api","GET",context("/shop"),List.of(endpoint("api","/api","GET")),false).confidence());assertEquals(Confidence.UNRESOLVED,UrlResolution.resolve("{pageContext.request.contextPath}/api","GET",context(),List.of(endpoint("api","/api","GET")),true).confidence());}
 @Test void multipleContextsListAllCandidatesEvenIfRoutesConverge(){var r=UrlResolution.resolve("/a/api","GET",context("/a","/b"),List.of(endpoint("one","/api","GET"),endpoint("two","/a/api","GET")),false);assertEquals(Confidence.AMBIGUOUS,r.confidence());assertEquals(List.of("one","two"),r.candidates());assertEquals(List.of("/a/api","/api"),r.paths());}
 @Test void externalAndTraversalPathsRemainUnresolved(){for(String url:List.of("https://host/api","//host/api","/../api","{unknown}/api")){var r=UrlResolution.resolve(url,"GET",context(""),List.of(endpoint("a","/api","GET")),false);assertEquals(Confidence.UNRESOLVED,r.confidence());assertTrue(r.candidates().isEmpty());}}
 @Test void readsPropertiesYamlWorkspaceValuesAndRetainsConflicts() throws Exception {var dir=root.resolve("src/main/resources");Files.createDirectories(dir);Files.writeString(dir.resolve("application.properties"),"server.servlet.context-path=/prop\n");Files.writeString(dir.resolve("application.yml"),"server:\n  servlet:\n    context-path: /yaml\n");var c=UrlResolution.context(new ProjectScanner().scan(root),context("/workspace").values());assertEquals(List.of("/prop","/workspace","/yaml"),c.values().stream().map(UrlResolution.ContextValue::value).toList());assertEquals(3,c.values().stream().map(v->v.source().file()).distinct().count());}
 @Test void unsafeYamlAndUnresolvedConfigurationProduceDiagnostics() throws Exception {Files.writeString(root.resolve("application.yml"),"!!java.net.URL ['https://example.invalid']");Files.writeString(root.resolve("application.properties"),"server.servlet.context-path=${DEPLOY_CONTEXT}\n");var c=UrlResolution.context(new ProjectScanner().scan(root),List.of());assertTrue(c.values().isEmpty());assertFalse(c.diagnostics().isEmpty());}
}
