package io.screentrace.cli;
import com.fasterxml.jackson.databind.*;
import io.screentrace.report.ComponentLibrary;
import java.nio.file.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
class ComponentLibraryTest {
 @TempDir Path temp;
 byte[] sample() throws Exception {return Files.readAllBytes(Path.of("../docs/examples/component-library.sample.json"));}
 @Test void schemaRejectsUnknownNestedFieldsAndLimits() throws Exception {var json=new ObjectMapper();var data=(com.fasterxml.jackson.databind.node.ObjectNode)json.readTree(sample());assertNotNull(ComponentLibrary.validate(sample()));((com.fasterxml.jackson.databind.node.ObjectNode)data.path("components").get(0)).put("unknown",1);assertTrue(assertThrows(IllegalArgumentException.class,()->ComponentLibrary.validate(json.writeValueAsBytes(data))).getMessage().contains("unknown"));assertThrows(IllegalArgumentException.class,()->ComponentLibrary.validate(new byte[5*1024*1024+1]));data.remove("components");assertThrows(IllegalArgumentException.class,()->ComponentLibrary.validate(json.writeValueAsBytes(data)));}
 @Test void storedOnlyBindingReplacementUnbindAndPrivacy() throws Exception {var store=new LibraryStore(temp);var first=store.importManifest(sample(),null,false);assertTrue(first.contains("尚未綁定任何專案"));assertNull(store.selected("demo"));assertTrue(store.list().contains("Sample"));store.importManifest(sample(),"demo",false);var selected=store.selected("demo");assertEquals(64,selected.sha256().length());assertFalse(store.list().contains(temp.toString()));var changed=new String(sample()).replace("Sample Library","Sample Changed Description").getBytes(java.nio.charset.StandardCharsets.UTF_8);assertThrows(IllegalArgumentException.class,()->store.importManifest(changed,"demo",false));assertTrue(store.importManifest(changed,"demo",true).contains("重新產生報表"));assertNotEquals(selected.sha256(),store.selected("demo").sha256());assertTrue(store.list().contains(selected.sha256().substring(0,12)));assertTrue(store.list().contains(store.selected("demo").sha256().substring(0,12)));store.unbind("demo");assertNull(store.selected("demo"));assertFalse(store.list().contains(System.getProperty("user.home")));}
 @Test void commandErrorsDoNotExposePaths() throws Exception {assertThrows(IllegalArgumentException.class,()->LibraryCommands.run(new String[]{"library","bad"},temp));var out=LibraryCommands.run(new String[]{"library","validate","/Users/private/absent.json"},temp);assertFalse(out.contains("/Users/private"));assertTrue(out.contains("失敗"));}
 @Test void componentLimitDuplicateIdsAndPrivateTextAreRejected() throws Exception {var json=new ObjectMapper();var data=(com.fasterxml.jackson.databind.node.ObjectNode)json.readTree(sample());var list=(com.fasterxml.jackson.databind.node.ArrayNode)data.get("components");var base=list.get(0).deepCopy();for(int i=1;i<=2000;i++){var c=(com.fasterxml.jackson.databind.node.ObjectNode)base.deepCopy();c.put("id","sample-"+i);list.add(c);}assertThrows(IllegalArgumentException.class,()->ComponentLibrary.validate(json.writeValueAsBytes(data)));list.removeAll();list.add(base);list.add(base);assertTrue(assertThrows(IllegalArgumentException.class,()->ComponentLibrary.validate(json.writeValueAsBytes(data))).getMessage().contains("ID"));list.remove(1);((com.fasterxml.jackson.databind.node.ObjectNode)base).put("description",System.getProperty("user.home")+"/secret");String error=assertThrows(IllegalArgumentException.class,()->ComponentLibrary.validate(json.writeValueAsBytes(data))).getMessage();assertFalse(error.contains(System.getProperty("user.home")));}

 @Test void manifestSymlinkCannotBeValidatedOrImported() throws Exception {Path source=temp.resolve("manifest.json"),link=temp.resolve("link.json");Files.write(source,sample());Files.createSymbolicLink(link,source);String validate=LibraryCommands.run(new String[]{"library","validate",link.toString()},temp);assertTrue(validate.contains("失敗"));String imported=LibraryCommands.run(new String[]{"library","import",link.toString()},temp);assertTrue(imported.contains("失敗"));assertEquals("",new LibraryStore(temp).list());}

 @Test void priorityMustBeExactlyRepresentableForDeterministicJavaScriptMatching() throws Exception {var json=new ObjectMapper();var data=json.readTree(sample());((com.fasterxml.jackson.databind.node.ObjectNode)data.path("components").get(0).path("matches").get(0)).put("priority",9007199254740992L);assertTrue(assertThrows(IllegalArgumentException.class,()->ComponentLibrary.validate(json.writeValueAsBytes(data))).getMessage().contains("priority"));}

}
