package io.screentrace.cli;
import static org.junit.jupiter.api.Assertions.*;
import io.screentrace.core.*;import io.screentrace.report.*;import java.nio.file.*;import java.util.*;import java.lang.reflect.*;import org.junit.jupiter.api.Test;
class MarkdownRetirementTest {
 private static Path root(){for(Path p=Path.of("").toAbsolutePath();p!=null;p=p.getParent())if(Files.isRegularFile(p.resolve("pom.xml"))&&Files.isDirectory(p.resolve("screentrace-core")))return p;throw new IllegalStateException("Source root missing");}
 @Test void exportCommandIsRejectedBeforeAnyConsoleOrFilesystemWork() throws Exception {var command=Arrays.stream(ScreenTraceCli.class.getDeclaredClasses()).filter(c->c.getSimpleName().equals("Command")).findFirst().orElseThrow();var parse=command.getDeclaredMethod("parse",String[].class);parse.setAccessible(true);var error=assertThrows(InvocationTargetException.class,()->parse.invoke(null,(Object)new String[]{"export","project"}));assertInstanceOf(IllegalArgumentException.class,error.getCause());assertFalse(error.getCause().getMessage().contains("|export"));for(var action:List.of("analyze","report","config"))assertNotNull(parse.invoke(null,(Object)new String[]{action}));}
 @Test void legacyGeneratorAndItsContractsAreRetired() throws Exception {for(var path:List.of("screentrace-report/src/main/java/io/screentrace/report/ReviewResultGenerator.java","screentrace-report/src/test/java/io/screentrace/report/ReviewResultGeneratorTest.java","screentrace-cli/src/test/java/io/screentrace/cli/ReviewExportContractTest.java","docs/REVIEW_RESULT_CONTRACT.md","docs/examples/review-result.json"))assertFalse(Files.exists(root().resolve(path)),path);var cli=Files.readString(root().resolve("screentrace-cli/src/main/java/io/screentrace/cli/ScreenTraceCli.java"));assertFalse(cli.contains("ReviewResultGenerator"));assertFalse(cli.contains("Action.EXPORT"));assertFalse(Files.readString(root().resolve("README.md")).contains("review-result.json"));assertTrue(Files.isRegularFile(root().resolve("docs/REVIEW_MD_CONTRACT.md")));assertThrows(ClassNotFoundException.class,()->Class.forName("io.screentrace.report.ReviewResultGenerator"));}
 @Test void analysisDoesNotInitializeLegacyReviewFilesAndPreservesExistingUserData() throws Exception {var graph=new ApplicationGraph(new ApplicationGraph.Application("empty",".",List.of()),List.of(),List.of(),List.of(),List.of(),"2.2",List.of(),List.of());var output=Files.createTempDirectory("md-retirement");var writer=new SingleHtmlAnalysisWriter();writer.prepare(graph,output);assertFalse(Files.exists(output.resolve("edit-overlay.json")));assertFalse(Files.exists(output.resolve("review-result.json")));assertEquals("2.2",new com.fasterxml.jackson.databind.ObjectMapper().readTree(output.resolve("application-graph.json").toFile()).path("schemaVersion").asText());Files.writeString(output.resolve("edit-overlay.json"),"user-owned-history");writer.prepare(graph,output);assertEquals("user-owned-history",Files.readString(output.resolve("edit-overlay.json")));}
}
