import {setDecision} from './decision-controls.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp,truncate,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {chromium,firefox,webkit} from '../../screentrace-capture/node_modules/playwright/index.mjs';import {fileFixture,node} from './fixture.mjs';import {mdFixture} from './md-fixture.mjs';
const engines=process.env.ST_BROWSERS?.split(',')||['chromium'];
const normalized=md=>md.replace(/^generated_at: .*$/m,'generated_at: "TIME"');
async function download(page){const wait=page.waitForEvent('download');await page.getByRole('button',{name:'匯出 md',exact:true}).click();const file=await wait;assert.equal(file.suggestedFilename(),'screentrace-review.md');return readFile(await file.path(),'utf8');}
async function upload(page,md){await page.getByLabel('匯入 md',{exact:true}).setInputFiles({name:'review.md',mimeType:'text/markdown',buffer:Buffer.from(md)});}
for(const engine of engines){
 test(`${engine}: review mark/export/clear/import/export is byte-identical except timestamp and has no requests`,async()=>{const browser=await({chromium,firefox,webkit}[engine]).launch();try{const page=await browser.newPage(),data=mdFixture(),requests=[];const file=await fileFixture(data);page.on('request',r=>{if(r.url()!==file&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))requests.push(r.url());});await page.goto(file);await page.getByRole('checkbox',{name:'確認模式',exact:true}).check();await setDecision(page.locator('[data-screen-review="a"]'),'KEEP');await page.locator('.screen-card[data-screen="a"]').click();await setDecision(page.locator('[data-component-review="shared"]'),'KEEP');await page.getByRole('button',{name:'地圖',exact:true}).click();await setDecision(page.locator('[data-screen-review="b"]'),'REMOVE');await page.locator('.screen-card[data-screen="b"]').click();await setDecision(page.locator('[data-component-review="shared"]'),'REMOVE');const first=await download(page);assert.match(first,/format_version/);await page.evaluate(()=>localStorage.clear());await page.reload();await page.getByRole('checkbox',{name:'確認模式',exact:true}).check();assert.equal(await page.locator('[data-screen-review="a"]').getAttribute('data-decision'),'UNDECIDED');await upload(page,first);await page.locator('[data-md-status]').filter({hasText:'匯入完成'}).waitFor();assert.equal(await page.locator('[data-screen-review="a"]').getAttribute('data-decision'),'KEEP');assert.equal(await page.locator('[data-screen-review="b"]').getAttribute('data-decision'),'REMOVE');await page.locator('.screen-card[data-screen="a"]').click();assert.equal(await page.locator('[data-component-review="shared"]').getAttribute('data-decision'),'KEEP');await page.getByRole('button',{name:'地圖',exact:true}).click();await page.locator('.screen-card[data-screen="b"]').click();assert.equal(await page.locator('[data-component-review="shared"]').getAttribute('data-decision'),'REMOVE');assert.equal(normalized(await download(page)),normalized(first));assert.deepEqual(requests,[]);}finally{await browser.close();}});
 test(`${engine}: malformed, modified and truncated imports preserve current decisions`,async()=>{const browser=await({chromium,firefox,webkit}[engine]).launch();try{const page=await browser.newPage();await page.goto(await fileFixture(mdFixture()));await page.getByRole('checkbox',{name:'確認模式',exact:true}).check();await setDecision(page.locator('[data-screen-review="a"]'),'KEEP');const original=await download(page);for(const invalid of ['bad markdown',original.replace('"KEEP"','"REMOVE"'),original.slice(0,-12),original+'\nEXTRA']){await upload(page,invalid);await page.locator('[data-md-status]').filter({hasText:'匯入失敗'}).waitFor();assert.equal(await page.locator('[data-screen-review="a"]').getAttribute('data-decision'),'KEEP');assert.equal(normalized(await download(page)),normalized(original));}}finally{await browser.close();}});
 test(`${engine}: changed analysis lists every orphan and preserves unknown composite IDs`,async()=>{const browser=await({chromium,firefox,webkit}[engine]).launch();try{const page=await browser.newPage(),data=mdFixture();await page.goto(await fileFixture(data));await page.getByRole('checkbox',{name:'確認模式',exact:true}).check();await page.locator('.screen-card[data-screen="a"]').click();await setDecision(page.locator('[data-component-review="shared"]'),'KEEP');const md=await download(page);const changed=mdFixture();changed.fingerprint='b'.repeat(64);changed.graph.nodes=changed.graph.nodes.filter(n=>n.id!=='shared');changed.graph.relationships=changed.graph.relationships.filter(e=>e.from!=='shared'&&e.to!=='shared');changed.graph.behaviors=changed.graph.behaviors.filter(b=>b.triggerId!=='shared');changed.preview.elements=[];await page.goto(await fileFixture(changed));await upload(page,md);await page.locator('[data-md-status]').filter({hasText:'分析結果已變更'}).waitFor();assert.match(await page.locator('[data-md-orphans]').innerText(),/a.*shared/s);const exported=await download(page);assert.match(exported,/"component_decisions":\{"a":\{"shared":"KEEP"\}\}/);assert.match(exported,/'?b{64}'?/);}finally{await browser.close();}});
}
test('actual md over five MB warns and remains complete, including its final state block',async()=>{const data=mdFixture();for(let i=0;i<1000;i++){const id=`large-${i}`;data.graph.nodes.push(node(id,'COMPONENT','x'.repeat(300),{kind:'BUTTON'}));data.graph.relationships.push({id:`edge-${id}`,type:'CONTAINS',from:'a',to:id,confidence:'CONFIRMED',source:{file:'large.jsp',line:1},evidence:[{parser:'Fixture',resolution:'CONFIRMED',source:{file:'large.jsp',line:1}}]});data.preview.elements.push({graphScreenId:'a',graphComponentId:id,path:id,tag:'button',text:'button',bounds:{x:0,y:0,width:10,height:10},styleId:id,defaultId:'default',source:{file:'large.jsp',line:1}});data.preview.styles[id]=Object.fromEntries(Array.from({length:20},(_,j)=>[`--p${j}`,'v'.repeat(300)]));}const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto(await fileFixture(data));const md=await download(page);assert.ok(Buffer.byteLength(md)>5_000_000);assert.match(await page.locator('[data-md-status]').innerText(),/超過 5 MB.*完整/);assert.match(md,/## 附錄 A\. review state[\s\S]*\n```\n$/);assert.ok(md.includes('large-999'));}finally{await browser.close();}});

test('selected files above 64 MiB fail before reading and preserve current decisions',async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'screentrace-md-cap-')),file=path.join(directory,'oversize.md');await writeFile(file,'');await truncate(file,64*1024*1024+1);
 const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto(await fileFixture(mdFixture()));await page.getByRole('checkbox',{name:'確認模式',exact:true}).check();await setDecision(page.locator('[data-screen-review="a"]'),'KEEP');
 await page.evaluate(()=>{globalThis.fileReads=0;File.prototype.text=function(){globalThis.fileReads++;throw Error('file must not be read');};});
 await page.getByLabel('匯入 md',{exact:true}).setInputFiles(file);await page.locator('[data-md-status]').filter({hasText:'匯入失敗'}).waitFor();assert.match(await page.locator('[data-md-status]').innerText(),/超過 64 MiB 安全上限/);assert.equal(await page.evaluate(()=>globalThis.fileReads),0);assert.equal(await page.locator('[data-screen-review="a"]').getAttribute('data-decision'),'KEEP');
 await page.evaluate(()=>{const input=document.querySelector('input[type=file]');Object.defineProperty(input,'files',{value:[{size:64*1024*1024,text(){globalThis.fileReads++;throw Error('exact limit reached reader');}}]});input.dispatchEvent(new Event('change'));});assert.match(await page.locator('[data-md-status]').innerText(),/exact limit reached reader/);assert.equal(await page.evaluate(()=>globalThis.fileReads),1);assert.equal(await page.locator('[data-screen-review="a"]').getAttribute('data-decision'),'KEEP');
 }finally{await browser.close();await rm(directory,{recursive:true,force:true});}
});
