import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from '../../screentrace-capture/node_modules/playwright/index.mjs';import {build} from 'esbuild';import {readFile} from 'node:fs/promises';import {submitFixture} from './wp29-submit-fixture.mjs';
for(const family of ['synthetic-petclinic-style','struts1','struts1-spring','spring-mvc-jsp','spring-boot-jsp'])test(`WP29 submit consistency: every operable element in ${family}`,async()=>{
 let payload=submitFixture();if(family!=='synthetic-petclinic-style'){const html=await readFile(new URL(`../../screentrace-cli/target/wp10-fixtures/${family}/first/report/screentrace-report.html`,import.meta.url),'utf8');const match=html.match(/<script[^>]*id="st-data"[^>]*>([\s\S]*?)<\/script>/);assert.ok(match);payload=JSON.parse(match[1]);}
 const browser=await chromium.launch();try{const page=await browser.newPage();for(const [name,globalName]of [['simulation-ui','coverage'],['simulation','simulation'],['preview','preview'],['inert-document','inert']]){const bundle=await build({entryPoints:[new URL(`../src/${name}.ts`,import.meta.url).pathname],bundle:true,format:'iife',globalName,write:false});await page.addScriptTag({content:bundle.outputFiles[0].text});}
 const result=await page.evaluate(p=>{const items=[];for(const screen of p.graph.nodes.filter(n=>n.type==='SCREEN')){const doc=inert.inertDocument(p.documents[screen.id]||''),dialogIds=(p.preview.elements||[]).filter(r=>r.graphScreenId===screen.id&&r.graphComponentId&&r.componentResolution!=='AMBIGUOUS'&&r.componentResolution!=='UNRESOLVED'&&doc.querySelector(preview.previewSelector(r.path))).map(r=>r.graphComponentId);for(const node of doc.querySelectorAll('a,button,form,select,input,textarea')){
 // Observe the current actual click path: a submit control invokes its associated form.
 const submit=node.localName==='button'&&(!node.getAttribute('type')||node.getAttribute('type')==='submit')||node.localName==='input'&&['submit','image'].includes(node.getAttribute('type')||'');const actualNode=submit&&node.form?node.form:node;
 const actual=simulation.simulate(p,screen.id,preview.previewElement(p,screen.id,actualNode),{tag:actualNode.localName,href:actualNode.getAttribute('href')||undefined,valid:true,dialogIds});const count=coverage.elementSimulationAssessment(p,screen.id,node,dialogIds);items.push({screen:screen.id,id:node.id,tag:node.localName,actual,possible:count.possible,expected:simulation.canSimulate(actual)});
 }}return items;},payload);
 assert.ok(result.length);const mismatches=result.filter(r=>r.possible!==r.expected);assert.deepEqual(mismatches,[],`${family}: coverage must equal the actual simulation result`);
 if(family==='synthetic-petclinic-style')for(const id of ['find-owner','add-visit','submit-input','submit-image','outside-submit'])assert.equal(result.find(r=>r.id===id).expected,true,id);
 }finally{await browser.close();}
});
