import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from '../../screentrace-capture/node_modules/playwright/index.mjs';import {build} from 'esbuild';import {readFile} from 'node:fs/promises';import {fileFixture,fixture} from './fixture.mjs';import {simulationFixture} from './wp26-fixture.mjs';
const total=r=>Object.values(r).reduce((a,b)=>a+b,0);
test('WP29 per-screen and project reason totals are invariant for synthetic cases and all four families',async()=>{
 const module=await build({entryPoints:[new URL('../src/simulation-ui.ts',import.meta.url).pathname],bundle:true,format:'iife',globalName:'coverage',write:false});const browser=await chromium.launch();try{const page=await browser.newPage();await page.addScriptTag({content:module.outputFiles[0].text});
 const cases=[simulationFixture()];const p=fixture(),vectors=JSON.parse(await readFile(new URL('../../fixtures/r7/coverage/mapped-reasons.json',import.meta.url)));p.documents.a='<body>'+vectors.cases.map(v=>`<${v.tag} id="${v.name}"${v.name==='hidden'?' type="hidden"':''}>Example</${v.tag}>`).join('')+'</body>';p.preview.elements=vectors.cases.map((v,i)=>({graphScreenId:'a',path:`body>${v.tag}[${vectors.cases.slice(0,i+1).filter(c=>c.tag===v.tag).length}]`,tag:v.tag,graphComponentId:v.name,componentResolution:'INFERRED'}));p.graph.nodes.push(...vectors.cases.map(v=>({id:v.name,type:'COMPONENT',attributes:{},name:v.name,confidence:'INFERRED'})));p.graph.relationships.push(...vectors.cases.map(v=>({type:'CONTAINS',from:'a',to:v.name})));p.graph.behaviors=vectors.cases.filter(v=>v.type).map(v=>({id:v.name,triggerId:v.name,type:v.type,event:v.event,targetId:v.target,evidence:[{parser:'Fixture',resolution:v.resolution,detail:v.resolution==='AMBIGUOUS'?'候選：[missing1, missing2]':''}]}));cases.push(p);
 for(const family of ['struts1','struts1-spring','spring-mvc-jsp','spring-boot-jsp']){const html=await readFile(new URL(`../../screentrace-cli/target/wp10-fixtures/${family}/first/report/screentrace-report.html`,import.meta.url),'utf8');const match=html.match(/<script[^>]*id="st-data"[^>]*>([\s\S]*?)<\/script>/);assert.ok(match,family);cases.push(JSON.parse(match[1]));}
 for(const payload of cases){const result=await page.evaluate(p=>({screens:p.graph.nodes.filter(n=>n.type==='SCREEN').map(n=>coverage.simulationCoverage(p,n.id)),project:coverage.projectSimulationCoverage(p)}),payload);for(const c of [...result.screens,result.project]){assert.equal(total(c.reasons),c.unknown);assert.equal(c.total,c.simulatable+c.editable+c.unknown);}const sums={};for(const c of result.screens)for(const[k,v]of Object.entries(c.reasons))sums[k]=(sums[k]||0)+v;assert.deepEqual(sums,result.project.reasons);}
 }finally{await browser.close();}
});
test('WP29 Chinese coverage and click explanations keep unsupported operations unexecuted',async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({reducedMotion:'reduce'}),requests=[];const url=await fileFixture(simulationFixture());page.on('request',r=>{if(!/^(data:|blob:)/.test(r.url())&&r.url()!==url)requests.push(r.url());});await page.goto(url);await page.locator('[data-screen-list=a]').click();await page.locator('.preview[aria-busy=false]').waitFor();assert.match(await page.locator('.simulation-coverage-reasons:visible').innerText(),/無法確認.*沒有已知的行為|無法確認.*分析器未建立元件/);await page.frameLocator('iframe').locator('#unmapped').click();assert.match(await page.locator('.prototype-status').innerText(),/分析器未建立元件/);await page.frameLocator('iframe').locator('#open').click();assert.equal(await page.locator('.element-unconfirmed-reason').count(),0,'mapped modal with available DOM is simulatable');await page.frameLocator('iframe').getByRole('button',{name:'關閉模擬彈窗'}).click();await page.frameLocator('iframe').locator('#name').click();assert.equal(await page.locator('.element-unconfirmed-reason').count(),0,'native editable inputs are not unknown');assert.deepEqual(requests,[]);}finally{await browser.close();}});
