import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from '../../screentrace-capture/node_modules/playwright/index.mjs';
import {fileFixture,node,fixture} from './fixture.mjs';

test('WP36 button page filters, expands shared navigation decisions, batches marks and returns with filters',async()=>{
 const payload=fixture();payload.graph.nodes.push(node('global-nav','COMPONENT','首頁導覽',{kind:'LINK',tag:'a'}));payload.graph.relationships.push({id:'global-nav-a',type:'CONTAINS',from:'a',to:'global-nav',confidence:'CONFIRMED'},{id:'global-nav-b',type:'CONTAINS',from:'b',to:'global-nav',confidence:'CONFIRMED'},{id:'global-nav-target',type:'NAVIGATES_TO',from:'global-nav',to:'b',confidence:'CONFIRMED'});
 const browser=await chromium.launch();try{const page=await browser.newPage(),url=await fileFixture(payload);await page.goto(url);await page.locator('#app[data-ready=true]').waitFor();await page.getByRole('button',{name:'按鈕',exact:true}).click();await page.locator('.button-table').waitFor();assert.ok(await page.locator('[data-button-row^="global:"]').count());await page.locator('[data-button-row^="global:"] .button-row-open').click();assert.ok(await page.locator('.button-global-member').count()>=2);
  await page.getByRole('checkbox',{name:'確認模式',exact:true}).check();await page.getByLabel('依動作類型').selectOption('連結');assert.ok(await page.locator('.button-table tbody tr[data-button-row]').count()>=1);for(const type of await page.locator('.button-table tbody tr[data-button-row] td:nth-child(3)').allTextContents())assert.equal(type,'連結');await page.getByLabel('依動作類型').selectOption('');await page.getByLabel('排序').selectOption('name');const checks=page.locator('.button-table tbody tr[data-button-row] input[type=checkbox]');assert.ok(await checks.count()>=2);await checks.first().check();await checks.nth(1).check();await page.getByRole('button',{name:'套用批次標記'}).click();await page.getByLabel('依確認狀態').selectOption('KEEP');assert.ok(await page.locator('.button-table tbody tr[data-button-row]').count()>=1);await page.getByLabel('依確認狀態').selectOption('ALL');const search=page.getByRole('searchbox',{name:'搜尋按鈕總表'});await search.fill('共用按鈕');await page.locator('.button-table tbody tr[data-button-row]').first().waitFor();
  await page.locator('.button-table tbody tr[data-button-row] .button-row-open').first().click();await page.getByRole('button',{name:'返回按鈕總表'}).click();assert.equal(await search.inputValue(),'共用按鈕');assert.equal(await page.locator('.button-table tbody tr[data-button-row]').count(),2);
 }finally{await browser.close();}
});
