import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from '../../screentrace-capture/node_modules/playwright/index.mjs';
import {fileFixture,fixture,node} from './fixture.mjs';

test('WP38 flow outline, global search, first-run guide and help can be used without changing decisions',async()=>{
 const data=fixture();data.documents.a=data.documents.a.replace('id="shared"','id="shared" data-st-component-id="shared"');data.graph.nodes.push(node('c','SCREEN','Owner Details',{route:'/owners/7'}),node('find','COMPONENT','Find Owner',{kind:'BUTTON',tag:'button'}));data.graph.nodes.push(node('api-owner','ENDPOINT','Owner API',{path:'/api/owners',httpMethod:'GET'}));data.graph.relationships.push({id:'find-owner',type:'CONTAINS',from:'a',to:'find'},{id:'find-api',type:'CALLS',from:'find',to:'api-owner'});data.graph.behaviors.push({id:'go-owner',triggerId:'shared',type:'NAVIGATE',targetId:'c',event:'click',confidence:'CONFIRMED'});
 const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto(await fileFixture(data));await page.waitForSelector('[data-ready="true"]');
  const guide=page.locator('[data-first-run-guide]');await guide.waitFor();for(const phrase of ['瀏覽地圖','點畫面看完整頁','試操作','隨時標記並匯出']){assert.match(await guide.innerText(),new RegExp(phrase));if(phrase!=='隨時標記並匯出')await guide.getByRole('button',{name:'下一步'}).click();}await guide.getByRole('button',{name:'略過'}).click();await guide.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(key=>key.startsWith('screentrace:review:'))),false,'guide actions do not write review decisions');
  await page.keyboard.press('/');assert.equal(await page.getByRole('textbox',{name:'搜尋 URL 或路徑'}).evaluate(e=>e===document.activeElement),true);await page.getByRole('button',{name:'全域搜尋'}).click();const search=page.getByRole('searchbox',{name:'全域搜尋'});await search.waitFor();await search.fill('Owner');assert.ok(await page.locator('[data-global-result="screen"]').count());assert.ok(await page.locator('[data-global-result="button"]').count());await search.fill('/api/owners');assert.ok(await page.locator('[data-global-result="api"]').count());await page.locator('[data-global-result="api"]').first().click();await page.locator('.api-row [aria-pressed="true"]').waitFor();
  await page.keyboard.press('Control+k');await search.fill('共用按鈕');await page.locator('[data-global-result="button"]').click();await page.locator('.prototype-viewer').waitFor();await page.waitForFunction(()=>document.querySelector('main')?.dataset.reviewFocus==='a:shared'&&!!document.querySelector('iframe')?.contentDocument?.querySelector('#shared')?.style.outline);await page.keyboard.press('Control+k');await search.fill('Owner Details');await page.locator('[data-global-result="screen"]').click();await page.locator('.prototype-viewer').waitFor();await page.locator('.focus-breadcrumb.global-search-highlight').waitFor();assert.equal(await page.locator('.screen-card.search-match').count(),0);
  await page.getByRole('button',{name:'地圖',exact:true}).click();await page.locator('.screen-card[data-screen="a"]').click();const outline=page.locator('[data-flow-outline]');await outline.waitFor();assert.ok(await outline.locator('[data-flow-node]').count()>0);await outline.locator(':scope > summary').click();await outline.locator('[data-flow-node="c"] .flow-outline-link').first().click();await page.locator('main h2').filter({hasText:'Owner Details'}).waitFor();
  const help=page.locator('.review-help');await page.locator('.review-help>summary').click();await help.waitFor();assert.match(await help.innerText(),/快捷鍵|保留|未解析/);await help.getByRole('button',{name:'重新開啟引導'}).click();await guide.waitFor();
 }finally{await browser.close();}
});

test('WP38 first-run guide remains available on each launch when browser storage is unavailable',async()=>{const browser=await chromium.launch();try{const page=await browser.newPage();await page.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError')}});});await page.goto(await fileFixture());await page.waitForSelector('[data-ready="true"]');const guide=page.locator('[data-first-run-guide]');await guide.waitFor();await guide.getByRole('button',{name:'略過'}).click();await guide.waitFor({state:'hidden'});await page.reload();await guide.waitFor();}finally{await browser.close();}});

test('WP38 first-run guide does not intercept application controls',async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1440,height:900}});await page.goto(await fileFixture());await page.waitForSelector('[data-ready="true"]');await page.locator('[data-first-run-guide]').waitFor();await page.getByRole('button',{name:'API',exact:true}).click();await page.locator('.api-sorting>summary').click();assert.equal(await page.locator('.api-sorting').getAttribute('open'),'');}finally{await browser.close();}});
