import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from '../../screentrace-capture/node_modules/playwright/index.mjs';
import {fileFixture,fixture,node} from './fixture.mjs';

test('WP38 flow outline, global search, first-run guide and help can be used without changing decisions',async()=>{
 const data=fixture();data.documents.a=data.documents.a.replace('id="shared"','id="shared" data-st-component-id="shared"');data.graph.nodes.push(node('c','SCREEN','Owner Details',{route:'/owners/7'}),node('find','COMPONENT','Find Owner',{kind:'BUTTON',tag:'button'}));data.graph.nodes.push(node('api-owner','ENDPOINT','Owner API',{path:'/api/owners',httpMethod:'GET'}));data.graph.relationships.push({id:'find-owner',type:'CONTAINS',from:'a',to:'find'},{id:'find-api',type:'CALLS',from:'find',to:'api-owner'});data.graph.behaviors.push({id:'go-owner',triggerId:'shared',type:'NAVIGATE',targetId:'c',event:'click',confidence:'CONFIRMED'});
 const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto(await fileFixture(data));await page.waitForSelector('[data-ready="true"]');
  const guide=page.locator('[data-first-run-guide]');await guide.waitFor();for(const phrase of ['瀏覽地圖','點畫面看完整頁','試操作','隨時標記並匯出']){assert.match(await guide.innerText(),new RegExp(phrase));if(phrase!=='隨時標記並匯出')await guide.getByRole('button',{name:'下一步'}).click();}await guide.getByRole('button',{name:'略過'}).click();await guide.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(key=>key.startsWith('screentrace:review:'))),false,'guide actions do not write review decisions');
  await page.keyboard.press('/');assert.equal(await page.getByRole('textbox',{name:'搜尋 URL 或路徑'}).evaluate(e=>e===document.activeElement),true);await page.getByRole('button',{name:'全域搜尋'}).click();const search=page.getByRole('searchbox',{name:'全域搜尋'});await search.waitFor();await search.fill('Owner');assert.ok(await page.locator('[data-global-result="screen"]').count());assert.ok(await page.locator('[data-global-result="button"]').count());await search.fill('/api/owners');assert.ok(await page.locator('[data-global-result="api"]').count());await page.locator('[data-global-result="api"]').first().click();await page.locator('.api-row [aria-pressed="true"]').waitFor();
  await page.keyboard.press('Control+k');await search.fill('共用按鈕');await page.locator('[data-global-result="button"]').click();await page.locator('.prototype-viewer').waitFor();await page.waitForFunction(()=>document.querySelector('main')?.dataset.reviewFocus==='a:shared'&&!!document.querySelector('iframe')?.contentDocument?.querySelector('#shared')?.style.outline);await page.keyboard.press('Control+k');await search.fill('Owner Details');await page.locator('[data-global-result="screen"]').click();await page.locator('.prototype-viewer').waitFor();await page.locator('.focus-breadcrumb.global-search-highlight').waitFor();assert.equal(await page.locator('.screen-card.search-match').count(),0);
  await page.getByRole('button',{name:'地圖',exact:true}).click();await page.locator('.screen-card[data-screen="a"]').click();const outline=page.locator('[data-flow-outline]');await outline.waitFor();assert.equal(await outline.locator('[data-flow-node]').count(),0,'collapsed flow outline is deferred');await outline.locator(':scope > summary').click();await outline.locator('[data-flow-node="c"] .flow-outline-link').first().click();await page.locator('main h2').filter({hasText:'Owner Details'}).waitFor();
  const help=page.locator('.review-help');await page.locator('.topbar-more>summary').click();await page.locator('.review-help>summary').click();await help.waitFor();assert.match(await help.innerText(),/快捷鍵|保留|未解析/);await page.getByRole('menuitem',{name:'重新開啟引導'}).click();await guide.waitFor();
 }finally{await browser.close();}
});

test('WP41 first-run guide uses tab-session fallback when local storage is unavailable and can reopen in a new tab',async()=>{const browser=await chromium.launch();try{const page=await browser.newPage();await page.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError')}});});await page.goto(await fileFixture());await page.waitForSelector('[data-ready="true"]');const guide=page.locator('[data-first-run-guide]');await guide.waitFor();await guide.getByRole('button',{name:'略過'}).click();await guide.waitFor({state:'hidden'});await page.reload();await guide.waitFor({state:'hidden'});const newTab=await browser.newPage();await newTab.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError')}});});await newTab.goto(await fileFixture());await newTab.waitForSelector('[data-ready="true"]');await newTab.locator('[data-first-run-guide]').waitFor();}finally{await browser.close();}});

test('WP38 first-run guide does not intercept application controls',async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1440,height:900}});await page.goto(await fileFixture());await page.waitForSelector('[data-ready="true"]');await page.locator('[data-first-run-guide]').waitFor();await page.getByRole('button',{name:'API',exact:true}).click();await page.locator('.api-sorting>summary').click();assert.equal(await page.locator('.api-sorting').getAttribute('open'),'');}finally{await browser.close();}});

test('WP38 rendered flow tree expands each screen once, groups unknown outcomes and exposes only requester labels',async()=>{
 const data=fixture();data.graph.nodes.push(node('c','SCREEN','寵物表單',{route:'/pets/new'}),node('d','SCREEN','就診表單',{route:'/visits/new'}),
  node('add-owner-form','COMPONENT','add-owner-form',{kind:'FORM'}),node('generic-form','COMPONENT','表單 1',{kind:'FORM'}),node('generic-link','COMPONENT','連結 6',{kind:'LINK'}),node('readable','COMPONENT','編輯飼主',{kind:'LINK'}),node('unknown-one','COMPONENT','unknown-one',{kind:'BUTTON'}),node('unknown-two','COMPONENT','unknown-two',{kind:'LINK'}));
 data.graph.relationships.push({id:'owner-trigger',type:'CONTAINS',from:'a',to:'add-owner-form'},{id:'generic-form-owner',type:'CONTAINS',from:'a',to:'generic-form'},
  {id:'generic-link-owner',type:'CONTAINS',from:'a',to:'generic-link'},{id:'readable-owner',type:'CONTAINS',from:'b',to:'readable'},
  {id:'unknown-one-owner',type:'CONTAINS',from:'a',to:'unknown-one'},{id:'unknown-two-owner',type:'CONTAINS',from:'a',to:'unknown-two'},
  {id:'a-b',type:'NAVIGATES_TO',from:'add-owner-form',to:'b'},{id:'a-c',type:'NAVIGATES_TO',from:'generic-form',to:'c'},
  {id:'a-d-1',type:'NAVIGATES_TO',from:'generic-link',to:'d'},{id:'a-d-2',type:'NAVIGATES_TO',from:'generic-form',to:'d'},
  {id:'b-d',type:'NAVIGATES_TO',from:'readable',to:'d'});
 data.graph.behaviors.push({id:'unknown-1',triggerId:'unknown-one',type:'NAVIGATE',expression:'first()',confidence:'UNRESOLVED'},{id:'unknown-2',triggerId:'unknown-two',type:'NAVIGATE',expression:'second()',confidence:'UNRESOLVED'});
 const browser=await chromium.launch();try{const page=await browser.newPage();await page.goto(await fileFixture(data));await page.locator('[data-ready="true"]').waitFor();await page.locator('[data-screen-list="a"]').click();const tree=page.locator('[data-flow-outline]');await tree.locator(':scope > summary').click();await tree.locator('[data-flow-root="a"]').waitFor();
  assert.equal(await tree.locator('[data-flow-node="d"]:not([data-already-expanded])').count(),1);assert.equal(await tree.locator('[data-flow-node="d"][data-already-expanded="true"]').count(),1);assert.equal(await tree.locator('[data-unresolved="true"]').count(),1);
  const text=await tree.innerText();assert.match(text,/已在上面展開/);assert.match(text,/Add Owner Form 表單/);assert.match(text,/表單（無文字）/);assert.match(text,/連結（無文字）/);assert.doesNotMatch(text,/add-owner-form|表單 1|連結 6|unknown-one|unknown-two/);
  await tree.locator('[data-flow-node="d"][data-already-expanded="true"] .flow-outline-link').first().click();await page.locator('main h2').filter({hasText:'就診表單'}).waitFor();
 }finally{await browser.close();}
});
