import test from 'node:test';
import assert from 'node:assert/strict';
import {chromium} from '../../screentrace-capture/node_modules/playwright/index.mjs';
import {fileFixture,fixture} from './fixture.mjs';

test('WP39 viewer removes mode controls, keeps reset and zoom in an accessible overflow menu, and adds a style tab',async()=>{
 const data=fixture();data.graph.behaviors=[{id:'shared-nav',triggerId:'shared',type:'NAVIGATE',targetId:'b',event:'click',evidence:[{parser:'Fixture',resolution:'CONFIRMED',source:{file:'web/a.jsp',line:1}}]}];data.documents.a='<html><body><button id="shared">共用按鈕</button><button id="other">另一個按鈕</button><p id="copy">文字</p></body></html>';
 data.preview.elements=[{graphScreenId:'a',path:'html:nth-of-type(1)>body:nth-of-type(1)>button:nth-of-type(1)',tag:'button',text:'共用按鈕',graphComponentId:'shared',componentResolution:'CONFIRMED',bounds:{x:0,y:0,width:80,height:30},styleId:'button-style',defaultId:'button'},{graphScreenId:'a',path:'html:nth-of-type(1)>body:nth-of-type(1)>button:nth-of-type(2)',tag:'button',text:'另一個按鈕',bounds:{x:0,y:40,width:80,height:30},styleId:'other-style',defaultId:'button'},{graphScreenId:'a',path:'html:nth-of-type(1)>body:nth-of-type(1)>p:nth-of-type(1)',tag:'p',text:'文字',bounds:{x:0,y:80,width:80,height:20},styleId:'paragraph-style',defaultId:'p'}];data.preview.styles={'button-style':{color:'rgb(12, 34, 56)',fontWeight:'700'},'other-style':{color:'rgb(22, 44, 66)'},'paragraph-style':{color:'rgb(22, 44, 66)'}};data.preview.defaults={button:{display:'inline-block'},p:{display:'block'}};
 const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:1024,height:768},reducedMotion:'reduce'});const requests=[];page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await page.goto(await fileFixture(data));await page.locator('#app[data-ready=true]').waitFor();await page.locator('[data-screen-list="a"]').click();
  const toolbar=page.locator('.prototype-toolbar');assert.equal(await toolbar.getByRole('button',{name:/操作|檢查|顯示可操作元素|縮放/}).count(),0);assert.equal(await toolbar.locator('select').count(),0);assert.match(await toolbar.innerText(),/看流程/);assert.ok(await toolbar.locator('button:visible').count()<=7);assert.equal(await page.locator('aside [role=tab]').count(),5);
  await toolbar.locator('.prototype-more > summary').click();await page.getByRole('menuitem',{name:'重置',exact:true}).waitFor();await page.getByRole('menuitem',{name:'回到起點',exact:true}).waitFor();await page.getByRole('menuitem',{name:'縮放：75%',exact:true}).click();assert.equal(await page.locator('.prototype-viewer').getAttribute('data-scale'),'0.75');
  const frame=page.frameLocator('iframe');await page.waitForFunction(()=>document.querySelector('iframe')?.contentDocument?.querySelectorAll('.st-first-pulse').length===1);assert.equal(await frame.locator('#shared').evaluate(el=>getComputedStyle(el).animationName),'none');await frame.locator('#shared').hover();await frame.locator('#shared.st-preview-hover').waitFor();assert.match(await page.locator('aside').innerText(),/共用按鈕/);assert.equal(await frame.locator('#shared').getAttribute('data-prototype-selected'),null);
  await frame.locator('#shared').evaluate(el=>el.dispatchEvent(new MouseEvent('click',{bubbles:true,altKey:true})));assert.equal(await frame.locator('#shared').getAttribute('data-prototype-selected'),'true');assert.equal(await page.locator('.prototype-status').innerText(),'');await frame.locator('#shared').evaluate(el=>el.dispatchEvent(new MouseEvent('click',{bubbles:true,altKey:true})));assert.equal(await frame.locator('#shared').getAttribute('data-prototype-selected'),null);await frame.locator('#shared').evaluate(el=>el.dispatchEvent(new MouseEvent('click',{bubbles:true,altKey:true})));await frame.locator('#other').hover();await frame.locator('#other.st-preview-hover').waitFor();assert.equal(await frame.locator('#shared').getAttribute('data-prototype-selected'),'true');assert.match(await page.locator('aside').innerText(),/另一個按鈕/);await page.locator('#detail-tab-button-0').click();await page.locator('#detail-tab-button-3').hover();await page.waitForFunction(()=>document.querySelector('aside')?.innerText.includes('共用按鈕'));await frame.locator('#other').focus();await frame.locator('#other.st-preview-hover').waitFor();assert.equal(await frame.locator('#shared').getAttribute('data-prototype-selected'),'true');assert.match(await page.locator('aside').innerText(),/另一個按鈕/);await frame.locator('#other').evaluate(el=>el.blur());await page.waitForFunction(()=>document.querySelector('aside')?.innerText.includes('共用按鈕'));await page.locator('#detail-tab-button-3').click();assert.match(await page.locator('[data-detail-tab="3"]').innerText(),/rgb\(12, 34, 56\)/);assert.match(await page.locator('[data-detail-tab="3"]').innerText(),/fontWeight：700/);
  await page.keyboard.press('Escape');assert.equal(await frame.locator('#shared').getAttribute('data-prototype-selected'),null);await frame.locator('#shared').click();await page.locator('main h2').filter({hasText:'乙'}).waitFor();await page.locator('.prototype-outgoing').waitFor({state:'detached'});await page.getByRole('button',{name:'上一頁'}).click();await page.locator('.prototype-outgoing').waitFor({state:'detached'});assert.match(await page.locator('.prototype-url').innerText(),/owners/);await toolbar.locator('.prototype-more > summary').click();await page.getByRole('menuitem',{name:'重置',exact:true}).click();await page.locator('.prototype-outgoing').waitFor({state:'detached'});assert.match(await page.locator('.prototype-url').innerText(),/owners/);await frame.locator('#shared').dispatchEvent('pointerdown',{pointerType:'touch'});await page.waitForFunction(()=>document.querySelector('iframe')?.contentDocument?.querySelector('#shared')?.getAttribute('data-prototype-selected')==='true',{timeout:2000});await frame.locator('#shared').dispatchEvent('pointerup',{pointerType:'touch'});await frame.locator('#shared').dispatchEvent('click');assert.equal(await page.locator('.prototype-status').innerText(),'');await page.waitForFunction(()=>!document.querySelector('iframe')?.contentDocument?.querySelector('.st-first-pulse'),{timeout:2000});await page.locator('.screen-card[data-screen="a"]').count().then(async count=>{if(!count){await page.getByRole('button',{name:'返回總覽'}).click();await page.locator('.screen-card[data-screen="a"]').click();}});assert.equal(await page.locator('iframe').evaluate(f=>f.contentDocument?.querySelectorAll('.st-first-pulse').length),0);const toolbarBounds=await toolbar.boundingBox(),toolbarScroll=await toolbar.evaluate(el=>({width:el.scrollWidth,client:el.clientWidth,height:el.getBoundingClientRect().height}));assert.ok(toolbarScroll.width<=toolbarScroll.client+1,JSON.stringify(toolbarScroll));assert.ok(toolbarBounds.height<55,JSON.stringify(toolbarBounds));assert.deepEqual(requests,[]);assert.equal(await page.evaluate(()=>window.__targetProbe),undefined);
 }finally{await browser.close();}
});
