import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
await mkdir(new URL('./dist/',import.meta.url),{recursive:true});
const result=await build({entryPoints:[fileURLToPath(new URL('./src/main.ts',import.meta.url))],bundle:true,write:false,format:'iife',platform:'browser',target:['chrome120','firefox120','safari17'],minify:true,charset:'ascii',legalComments:'none'});
const script=result.outputFiles[0].text;
const pom=await readFile(new URL('../pom.xml',import.meta.url),'utf8');
const version=pom.match(/<version>([^<]+)<\/version>/)?.[1];if(!version)throw Error('Missing tool version');
if(/<\/script/i.test(script))throw Error('Bundle contains an unsafe script terminator');
for(const [name,content] of [['viewer.version',version],['viewer.js',script],['viewer.sha256',createHash('sha256').update(script).digest('base64')],['template.html',await readFile(new URL('./src/template.html',import.meta.url),'utf8')],['viewer.css',await readFile(new URL('./src/viewer.css',import.meta.url),'utf8')]])await writeFile(new URL('./dist/'+name,import.meta.url),content);
const md=await build({entryPoints:[fileURLToPath(new URL('./src/shared/review-md.ts',import.meta.url))],bundle:true,write:false,format:'esm',platform:'neutral',target:'es2022',charset:'ascii',legalComments:'none'});
await writeFile(new URL('./dist/review-md.mjs',import.meta.url),md.outputFiles[0].text);
