import {endpointGroup,EndpointGroup} from './endpoint-presentation';
import {Index} from './map';
import {ReviewState,deriveApiUsage} from './shared/review';
import {iconButton} from './shell-ui';
import {element,text} from './text';
type ApiRecord={id:string;group:EndpointGroup;category:string;method:string;path:string;handler:string;handlerNames:string[];status:string;callers:number;searchable:string};
let externalNoticeDismissed=false;
export function apiPage(index:Index,state:ReviewState,onDetail:(id:string)=>void,_onCaller?:(screenId:string,componentId?:string)=>void,sourceIndex:Index=index):HTMLElement {
 const root=element('section',undefined,'api-page');root.append(element('h2',text.apis));
 const toolbar=element('div',undefined,'api-toolbar'),search=element('input');search.type='text';search.setAttribute('aria-label',text.apiSearch);search.placeholder=text.apiSearch;
 const info=iconButton('靜態分析限制','info');info.title=text.external;toolbar.append(search,info);
 const notice=element('div',undefined,'api-limit-notice'),dismiss=iconButton('關閉靜態分析提醒','close');notice.append(element('p',text.external),dismiss);notice.hidden=externalNoticeDismissed;dismiss.onclick=()=>{externalNoticeDismissed=true;notice.hidden=true;};
 const labels={IN_USE:text.inUse,REMOVABLE:text.removable,UNREFERENCED:text.unreferenced},usage=deriveApiUsage(index.graph,state);
 const records:ApiRecord[]=index.graph.nodes.filter(n=>n.type==='ENDPOINT').map(n=>{const method=n.attributes.httpMethod||n.attributes.method||'ANY',path=n.attributes.path||n.attributes.route||n.name,handlers=(index.graph.relationships||[]).filter(e=>e.type==='HANDLED_BY'&&e.from===n.id).map(e=>index.nodes.get(e.to)).filter(Boolean),handlerNames=handlers.map(h=>h!.name).sort(),handler=handlers.map(h=>`${h!.name}${h!.source?` · ${h!.source.file}:${h!.source.line}`:''}`).sort().join('\n'),result=usage.get(n.id)!,searchable=[method,path,handler,labels[result.status],...result.callers.map(c=>`${index.nodes.get(c.screenId)?.name||''} ${c.componentId?index.nodes.get(c.componentId)?.name||'':''} ${c.componentId?sourceIndex.nodes.get(c.componentId)?.name||'':''}`)].join(' ').toLowerCase();return{id:n.id,group:endpointGroup(n),category:n.attributes.category||'未分類',method,path,handler,handlerNames,status:result.status,callers:result.callers.length,searchable};});
 const filters=element('div',undefined,'api-state-filters');filters.setAttribute('role','group');filters.setAttribute('aria-label',text.apiFilter);let status='ALL',sort='method',ascending=true,selected='',group:EndpointGroup='API';
 const groups=element('div',undefined,'api-category-filters');groups.setAttribute('role','group');groups.setAttribute('aria-label','端點分類');const grouped=()=>records.filter(r=>group==='ALL'||r.group===group);
 for(const [value,label]of [['API','API'],['SCREEN','頁面路由'],['ALL','全部端點'],['UNCLASSIFIED','未分類']]as [EndpointGroup,string][]){const button=element('button',`${label} ${value==='ALL'?records.length:records.filter(r=>r.group===value).length}`,'chip');button.dataset.endpointGroup=value;button.setAttribute('aria-pressed',String(value===group));button.onclick=()=>{group=value;groups.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render();};groups.append(button);}
 const total=element('p',`共 ${records.length} 個端點`),pages=element('button',`另有 ${records.filter(r=>r.group==='SCREEN').length} 個頁面路由`);pages.onclick=()=>groups.querySelector<HTMLButtonElement>('[data-endpoint-group=SCREEN]')!.click();toolbar.append(total,pages);
 for(const value of ['ALL','IN_USE','REMOVABLE','UNREFERENCED']as const){const button=element('button',`${value==='ALL'?text.all:labels[value]} ${value==='ALL'?records.length:records.filter(r=>r.status===value).length}`,'chip');button.dataset.apiFilter=value;button.setAttribute('aria-pressed',String(value==='ALL'));button.onclick=()=>{status=value;filters.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render();};filters.append(button);}
 const methodFilter=element('select');methodFilter.setAttribute('aria-label','API 方法篩選');for(const method of ['ALL',...[...new Set(records.map(r=>r.method))].sort()]){const option=element('option',method==='ALL'?'所有方法':method);option.value=method;methodFilter.append(option);}toolbar.append(methodFilter);
 const sorting=element('details',undefined,'api-sorting');sorting.append(element('summary','排序'));for(const [key,label]of [['method',text.method],['path',text.path],['handler',text.handlers],['status',text.status],['callers',text.callerCount]]){const button=element('button',label);button.setAttribute('aria-label',`${text.sortBy}${label}${text.sortSuffix}`);button.onclick=()=>{ascending=sort===key?!ascending:true;sort=key;render();};sorting.append(button);}toolbar.append(sorting);
 const list=element('div',undefined,'api-list');root.append(toolbar,groups,filters,notice,list);
 const render=()=>{for(const b of filters.querySelectorAll<HTMLButtonElement>('button')){const value=b.dataset.apiFilter!;b.textContent=`${value==='ALL'?text.all:labels[value as keyof typeof labels]} ${value==='ALL'?grouped().length:grouped().filter(r=>r.status===value).length}`;}pages.hidden=group!=='API';const query=search.value.toLowerCase(),rows=grouped().filter(r=>(status==='ALL'||r.status===status)&&(methodFilter.value==='ALL'||r.method===methodFilter.value)&&(!query||r.searchable.includes(query))).sort((a,b)=>{const left=a[sort as 'method'|'path'|'handler'|'status'|'callers'],right=b[sort as 'method'|'path'|'handler'|'status'|'callers'],comparison=left<right?-1:left>right?1:a.id<b.id?-1:a.id>b.id?1:0;return ascending?comparison:-comparison;});list.replaceChildren();if(!rows.length)list.append(element('p','沒有符合的 API','api-no-results'));for(const record of rows){const row=element('article',undefined,'api-row');row.dataset.apiRow=record.id;const button=element('button');button.setAttribute('aria-pressed',String(record.id===selected));const method=element('span',record.method,'method-badge');method.dataset.method=record.method;const path=element('span',record.path,'api-path');path.title=record.path;const state=element('span',labels[record.status as keyof typeof labels],'api-state-chip');state.dataset.apiStatus=record.status;const count=element('span',String(record.callers),'api-caller-count');count.title=`呼叫來源 ${record.callers} 個`;count.setAttribute('aria-label',count.title);button.append(method,path,state,count);if(record.group==='UNCLASSIFIED'||record.group==='API'&&record.category!=='REST_API')button.append(element('span',record.category,'api-category'));if(records.filter(r=>r.path===record.path).length>1){const names=element('span',record.handlerNames.join('、')||text.noHandler,'api-handler-tag');names.title=names.textContent!;button.append(names);}button.onclick=()=>{selected=record.id;list.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));onDetail(record.id);};row.append(button);list.append(row);}};
 search.oninput=render;methodFilter.onchange=render;render();return root;
}
