import {Index} from './map';
import {FeatureRegion} from './feature-regions';
import {ButtonRow,buttonTableRows} from './button-table';
import {ReviewState,Decision,componentDecision,effectiveComponent} from './shared/review';
import {decisionLabel} from './review-ui';
import {componentLabelsForScreen,isAction,kindName} from './labels';
import {element} from './text';

export interface ButtonTableState {query:string;region:string;screen:string;kind:string;decision:string;sort:'screen'|'name'|'status';scrollTop:number;selected:Set<string>}
export const emptyButtonTableState=():ButtonTableState=>({query:'',region:'',screen:'',kind:'',decision:'ALL',sort:'screen',scrollTop:0,selected:new Set()});
const order=(a:string,b:string)=>a<b?-1:a>b?1:0;
const DECISIONS:[Decision,string][]=[['KEEP','保留'],['REMOVE','移除'],['UNDECIDED','未確認']];
function quickDecisions(name:string,screenId:string,componentId:string,change:(value:Decision)=>void,active:Decision):HTMLElement {
 const controls=element('div',undefined,'button-quick-decisions');for(const [decision,label]of DECISIONS){const button=element('button',label);button.type='button';button.title=`${label}：${name}`;button.setAttribute('aria-label',label);button.setAttribute('aria-pressed',String(active===decision));button.dataset.quickDecision=decision;button.onclick=event=>{event.stopPropagation();change(decision);};controls.append(button);}return controls;
}
export function buttonTableView(index:Index,regions:FeatureRegion[],review:ReviewState,enabled:boolean,state:ButtonTableState,callbacks:{focus:(screenId:string,componentId:string)=>void;decision:(screenId:string,componentId:string,value:Decision)=>void;batch:(keys:{screenId:string;componentId:string}[],value:Decision)=>void}):HTMLElement{
 const root=element('section',undefined,'button-table-page');root.append(element('h1','按鈕總表'));
 const toolbar=element('div',undefined,'button-table-filters'),query=element('input');query.type='search';query.placeholder='搜尋按鈕、畫面、目的或 API';query.setAttribute('aria-label','搜尋按鈕總表');query.value=state.query;query.oninput=()=>{state.query=query.value;refresh();};toolbar.append(query);
 const select=(label:string,value:string,items:[string,string][],change:(value:string)=>void)=>{const wrap=element('label',label),control=element('select');control.setAttribute('aria-label',label);for(const [id,name]of items){const option=element('option',name);option.value=id;control.append(option);}control.value=value;control.onchange=()=>change(control.value);wrap.append(control);toolbar.append(wrap);return control;};
 select('依區域',state.region,[['','全部'],...regions.map(region=>[region.key,region.name] as [string,string])],value=>{state.region=value;refresh();});select('依畫面',state.screen,[['','全部'],...index.screens.map(screen=>[screen.id,screen.name] as [string,string])],value=>{state.screen=value;refresh();});select('依動作類型',state.kind,[['','全部'],...['按鈕','連結','表單送出','下拉選單','多選欄位','日期欄位','彈窗'].map(value=>[value,value] as [string,string])],value=>{state.kind=value;refresh();});select('依確認狀態',state.decision,[['ALL','全部'],['UNDECIDED','未確認'],['KEEP','保留'],['REMOVE','移除'],['INHERITED_REMOVE','隨畫面移除']],value=>{state.decision=value;refresh();});select('排序',state.sort,[['screen','畫面'],['name','名稱'],['status','狀態']],value=>{state.sort=value as ButtonTableState['sort'];refresh();});
 const bulk=element('div',undefined,'button-table-bulk');bulk.hidden=!enabled;const chosen=element('span','已選取 0 個');chosen.dataset.selectedCount='';const apply=element('select');apply.setAttribute('aria-label','套用批次標記');for(const [value,label]of DECISIONS){const option=element('option',label);option.value=value;apply.append(option);}const applyButton=element('button','套用批次標記');applyButton.onclick=()=>callbacks.batch([...state.selected].map(key=>{const [screenId,componentId]=JSON.parse(key);return {screenId,componentId};}),apply.value as Decision);bulk.append(chosen,apply,applyButton);root.append(toolbar,bulk);
 const scroll=element('div',undefined,'button-table-scroll');scroll.addEventListener('scroll',()=>{state.scrollTop=scroll.scrollTop;});root.append(scroll);
 const rows=buttonTableRows(index),members=(row:ButtonRow)=>row.members.filter(member=>{const screen=index.nodes.get(member.screenId)!,region=regions.find(item=>item.screenIds.includes(member.screenId));if(state.region&&region?.key!==state.region)return false;if(state.screen&&member.screenId!==state.screen)return false;if(state.kind&&row.kind!==state.kind)return false;if(state.decision!=='ALL'&&effectiveComponent(review,member.screenId,member.componentId)!==state.decision)return false;const queryText=[row.name,screen.name,index.routes.get(screen.id)?.join(' ')||'',row.primaryAction,row.possibleResults,componentLabelsForScreen(index,member.screenId).get(member.componentId)||''].join(' ').toLowerCase();return !state.query||queryText.includes(state.query.toLowerCase());});
 const refresh=()=>{const visible=rows.map(row=>({row,members:members(row)})).filter(item=>item.members.length).sort((a,b)=>state.sort==='name'?order(a.row.name,b.row.name):state.sort==='status'?order(effectiveComponent(review,a.row.members[0].screenId,a.row.members[0].componentId),effectiveComponent(review,b.row.members[0].screenId,b.row.members[0].componentId))||order(a.row.name,b.row.name):order(a.row.screenNames[0],b.row.screenNames[0])||order(a.row.kind,b.row.kind)||order(a.row.name,b.row.name));scroll.replaceChildren();const table=element('table',undefined,'button-table');const head=element('thead'),header=element('tr');for(const title of ['所在畫面','按鈕名稱','類型','主要動作與可能結果','確認狀態','操作'])header.append(element('th',title));head.append(header);table.append(head);const body=element('tbody');
  for(const {row,members:visibleMembers} of visible){const tr=element('tr');tr.dataset.buttonRow=row.key;const first=visibleMembers[0],screen=index.nodes.get(first.screenId)!,decisions=new Set(visibleMembers.map(member=>effectiveComponent(review,member.screenId,member.componentId))),status=decisions.size===1?decisionLabel([...decisions][0]):'各畫面分別確認';const location=element('td',row.global?`多個畫面（${visibleMembers.length}）`:screen.name);if(enabled){const box=element('input');box.type='checkbox';box.setAttribute('aria-label',`選取 ${row.name}`);box.checked=visibleMembers.every(member=>state.selected.has(JSON.stringify([member.screenId,member.componentId])));box.onclick=event=>event.stopPropagation();box.onchange=()=>{for(const member of visibleMembers){const key=JSON.stringify([member.screenId,member.componentId]);box.checked?state.selected.add(key):state.selected.delete(key);}chosen.textContent=`已選取 ${state.selected.size} 個`;};location.prepend(box);}const name=element('td',row.name),kind=element('td',row.kind);kind.classList.add('button-table-kind');const action=element('td',undefined,'button-table-action');action.append(element('strong',row.primaryAction,'button-primary-action'),element('span',row.possibleResults,'button-possible-results'));if(row.technicalDetails.length){const details=element('details',undefined,'button-technical-details');details.append(element('summary','技術細節'));const list=element('ul');for(const item of row.technicalDetails)list.append(element('li',item));details.append(list);action.append(details);}const stateCell=element('td',undefined,'button-table-status');stateCell.append(element('span',status,'button-row-status'));const controlCell=element('td',undefined,'button-table-controls'),actions=element('div',undefined,'button-row-actions'),open=element('button',row.global?'展開各畫面決策':'查看按鈕','button-row-open');open.onclick=event=>{event.stopPropagation();if(row.global){const details=tr.nextElementSibling as HTMLTableRowElement|null;if(details)details.hidden=!details.hidden;}else {state.scrollTop=scroll.scrollTop;callbacks.focus(first.screenId,first.componentId);}};actions.append(open);if(enabled&&!row.global)actions.append(quickDecisions(row.name,first.screenId,first.componentId,value=>callbacks.decision(first.screenId,first.componentId,value),componentDecision(review,first.screenId,first.componentId)));controlCell.append(actions);tr.append(location,name,kind,action,stateCell,controlCell);tr.onclick=()=>{if(!row.global){state.scrollTop=scroll.scrollTop;callbacks.focus(first.screenId,first.componentId);}};body.append(tr);
   if(row.global){const detail=element('tr',undefined,'button-global-members');detail.hidden=true;const td=element('td');td.colSpan=6;for(const member of visibleMembers){const item=element('div',undefined,'button-global-member'),component=index.nodes.get(member.componentId)!,memberScreen=index.nodes.get(member.screenId)!,displayName=componentLabelsForScreen(index,member.screenId).get(member.componentId)||kindName(component),jump=element('button',`${memberScreen.name} · ${displayName} · ${decisionLabel(effectiveComponent(review,member.screenId,member.componentId))}`);jump.dataset.buttonMember=member.screenId;jump.onclick=()=>{state.scrollTop=scroll.scrollTop;callbacks.focus(member.screenId,member.componentId);};item.append(jump);if(enabled)item.append(quickDecisions(displayName,member.screenId,member.componentId,value=>callbacks.decision(member.screenId,member.componentId,value),componentDecision(review,member.screenId,member.componentId)));td.append(item);}detail.append(td);body.append(detail);}
  }
  table.append(body);scroll.append(table);const fields=[...index.owners].flatMap(([componentId,screenIds])=>{const node=index.nodes.get(componentId);return node&&!isAction(index,node)&&!['FORM','TABLE'].includes(node.attributes.kind)?screenIds.map(screenId=>({screenId,componentId,name:componentLabelsForScreen(index,screenId).get(componentId)||kindName(node),kind:kindName(node)})):[];}).filter(field=>!state.screen||field.screenId===state.screen).filter(field=>!state.region||regions.find(region=>region.screenIds.includes(field.screenId))?.key===state.region).filter(field=>!state.query||`${field.name} ${index.nodes.get(field.screenId)?.name}`.toLowerCase().includes(state.query.toLowerCase()));if(fields.length){const group=element('details',undefined,'button-table-fields');group.append(element('summary',`欄位 ${fields.length} 個`));const list=element('ul');for(const field of fields)list.append(element('li',`${index.nodes.get(field.screenId)?.name} · ${field.name} · ${field.kind}`));group.append(list);scroll.append(group);}if(enabled){chosen.textContent=`已選取 ${state.selected.size} 個`;}}
 refresh();requestAnimationFrame(()=>{scroll.scrollTop=state.scrollTop;});return root;
}
