import {Index,Relation,layeredLayout,fileEntries,searchScreens} from './map';import {Payload} from './contracts';import {element,text} from './text';
export function canvas(index:Index,payload:Payload,query:string,onFocus:(id:string)=>void):HTMLElement{
 const viewport=element('div',undefined,'canvas');viewport.tabIndex=0;viewport.setAttribute('aria-label',text.canvas);
 const controls=element('div',undefined,'canvas-controls'),world=element('div',undefined,'world');let zoom=1,x=0,y=0;const update=()=>world.style.transform=`translate(${x}px, ${y}px) scale(${zoom})`;
 const change=(ratio:number)=>{zoom=Math.max(.1,Math.min(4,zoom*ratio));update();};
 for(const [label,action]of [[text.zoomIn,()=>change(1.2)],[text.zoomOut,()=>change(1/1.2)],[text.reset,()=>{zoom=1;x=y=0;update();}]]as const){const button=element('button',label);button.onclick=action;controls.append(button);}
 const positions=layeredLayout(index),matches=searchScreens(index,query),width=Math.max(800,...[...positions.values()].map(p=>p.x+300)),height=Math.max(600,...[...positions.values()].map(p=>p.y+180));world.style.width=`${width}px`;world.style.height=`${height}px`;
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width',String(width));svg.setAttribute('height',String(height));svg.classList.add('relations');
 for(const relation of index.relations){const a=positions.get(relation.from)!,b=positions.get(relation.to)!;const line=document.createElementNS(svg.namespaceURI,'path');line.setAttribute('d',`M${a.x+125},${a.y+70} C${a.x+250},${a.y+70} ${b.x-40},${b.y+70} ${b.x+125},${b.y+70}`);line.setAttribute('class','relation-line');line.setAttribute('tabindex','0');line.setAttribute('role','button');line.setAttribute('aria-label',`${index.nodes.get(relation.from)!.name} → ${index.nodes.get(relation.to)!.name}`);line.addEventListener('click',()=>onFocus(relation.to));line.addEventListener('keydown',event=>{if((event as KeyboardEvent).key==='Enter')onFocus(relation.to);});const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=(index.routes.get(relation.to)||[]).join('\n');line.append(title);svg.append(line);}
 world.append(svg);
 for(const screen of index.screens){const card=element('button',undefined,'screen-card');card.dataset.screen=screen.id;card.classList.toggle('search-match',!!query&&matches.has(screen.id));const p=positions.get(screen.id)!;card.style.left=`${p.x}px`;card.style.top=`${p.y}px`;card.append(element('strong',screen.name),element('span',(index.routes.get(screen.id)||[]).join('\n')));const thumb=payload.preview.screens?.find(s=>s.graphScreenId===screen.id)?.thumbnail;if(thumb?.startsWith('data:image/')){const img=element('img');img.src=thumb;img.alt=screen.name;card.append(img);}card.onclick=()=>onFocus(screen.id);world.append(card);}
 viewport.addEventListener('keydown',e=>{if(e.target!==viewport)return;const step=50;if(e.key==='+'||e.key==='=')change(1.2);else if(e.key==='-')change(1/1.2);else if(e.key==='ArrowLeft')x+=step;else if(e.key==='ArrowRight')x-=step;else if(e.key==='ArrowUp')y+=step;else if(e.key==='ArrowDown')y-=step;else return;e.preventDefault();update();});
 let dragging:{x:number;y:number}|undefined;viewport.addEventListener('pointerdown',e=>{if((e.target as Element).closest('button,.relation-line'))return;dragging={x:e.clientX,y:e.clientY};viewport.setPointerCapture(e.pointerId);});viewport.addEventListener('pointermove',e=>{if(!dragging)return;x+=e.clientX-dragging.x;y+=e.clientY-dragging.y;dragging={x:e.clientX,y:e.clientY};update();});viewport.addEventListener('pointerup',()=>{dragging=undefined;});viewport.addEventListener('pointercancel',()=>{dragging=undefined;});viewport.addEventListener('wheel',e=>{e.preventDefault();change(e.deltaY<0?1.1:1/1.1);},{passive:false});
 update();viewport.append(world,controls);return viewport;
}
export function fileTree(index:Index,query:string,onFocus:(id:string)=>void):HTMLElement{const root=element('div',undefined,'file-tree'),folders=new Map<string,HTMLElement>([['',root]]),matches=searchScreens(index,query);for(const item of fileEntries(index)){const parts=item.path.split('/');let current='';let parent:HTMLElement=root;for(const folder of parts.slice(0,-1)){current=current?current+'/'+folder:folder;if(!folders.has(current)){const details=element('details'),summary=element('summary',folder),children=element('div',undefined,'folder');details.open=true;details.append(summary,children);parent.append(details);folders.set(current,children);}parent=folders.get(current)!;}const button=element('button',`${parts.at(-1)} — ${index.nodes.get(item.screenId)!.name}`,'file-entry');button.dataset.screen=item.screenId;button.classList.toggle('search-match',!!query&&matches.has(item.screenId));button.onclick=()=>onFocus(item.screenId);parent.append(button);}return root;}
