import {kindNames,kindName,componentLabel,isAction} from './labels';
import {libraryDetails,libraryOverride} from './library-ui';
import {ReviewState} from './shared/review';
import {Index} from './map';
import {Payload,Behavior,ElementRecord,Rule,Node} from './contracts';
import {element,text} from './text';
import {callSources,screenBehaviors,rootTrigger,callerKind} from './usage';

const behaviorNames:Record<string,string>={NAVIGATE:'前往其他畫面',SUBMIT_FORM:'送出表單',CALL_API:'呼叫 API',OPEN_DIALOG:'開啟彈窗',VALIDATE:'執行資料檢核',UI_STATE_CHANGE:'變更畫面狀態',SELECT_CHANGE:'變更選項',UNKNOWN:'待確認的操作'};
const displayRoute=(value:string)=>value.replace(/\{([^}]+)\}/g,':$1');
const resolutionName=(value?:string)=>value==='UNRESOLVED'?'未解析':value==='AMBIGUOUS'?'有多個候選':value==='INFERRED'?'依證據推定':value==='CONFIRMED'?'已由來源確認':'待確認';
function resolution(index:Index,record:Node|Behavior):string {const states=(record.evidence||[]).map((e:any)=>e.resolution);return resolutionName(states.includes('AMBIGUOUS')?'AMBIGUOUS':states.includes('UNRESOLVED')?'UNRESOLVED':states.includes('INFERRED')?'INFERRED':states.includes('CONFIRMED')?'CONFIRMED':record.confidence);}
function tech(parent:HTMLElement,values:unknown[],open=false){const details=element('details',undefined,'technical-details');details.open=open;details.append(element('summary','技術細節'));for(const value of values)if(value!==undefined)details.append(element('pre',typeof value==='string'?value:JSON.stringify(value,null,2)));parent.append(details);}
function candidateNodes(index:Index,b:Behavior):Node[]{const ids=new Set<string>();for(const evidence of b.evidence||[]){for(const id of (evidence as any).candidates||[])if(typeof id==='string'&&index.nodes.has(id))ids.add(id);const detail=String((evidence as any).detail||'');for(const [id] of index.nodes)if(detail.includes(id))ids.add(id);}const details=(b.evidence||[]).map((e:any)=>String(e.detail||'')).join(' ');return [...ids].map(id=>index.nodes.get(id)!).sort((a,b)=>details.indexOf(a.id)-details.indexOf(b.id));}
function readableCandidate(node:Node):string[]{const parts:string[]=[];if(node.name&&node.name!==node.id)parts.push(node.name);const method=node.attributes.httpMethod||node.attributes.method,path=node.attributes.path||node.attributes.route;if(path)parts.push(`${method?`${method} `:''}${displayRoute(path)}`);const source=sourceText(node);if(source!=='來源位置未提供')parts.push(source);return parts;}
function sourceText(value:any):string {const source=value?.source||value?.evidence?.find((e:any)=>e.source)?.source;return source?`${source.file}:${source.line}`:'來源位置未提供';}
function actionSummary(index:Index,id:string):string[]{const values:string[]=[];for(const b of (index.graph.behaviors||[]).filter(b=>b.triggerId===id)){const target=index.nodes.get(b.targetId||'');const summary=behaviorNames[b.type]||'待確認的操作';values.push(target?.type==='SCREEN'?`前往「${target.name}」`:target?.type==='ENDPOINT'?`呼叫 ${target.attributes.httpMethod||target.attributes.method||'ANY'} ${target.attributes.path||target.name}`:summary);}for(const edge of (index.graph.relationships||[]).filter(e=>e.from===id&&['NAVIGATES_TO','TRIGGERS','CALLS'].includes(e.type))){const target=index.nodes.get(edge.to);if(target?.type==='SCREEN')values.push(`前往「${target.name}」`);else if(target?.type==='ENDPOINT')values.push(`呼叫 ${target.attributes.httpMethod||target.attributes.method||'ANY'} ${target.attributes.path||target.name}`);}return [...new Set(values)];}
function rulesFor(index:Index,screenId:string,componentId?:string):Rule[]{const n=index.nodes.get(componentId||screenId);return (index.graph.validationRules||[]).filter(r=>r.fields.includes(componentId||'')||!!n?.attributes.field&&r.fields.includes(n.attributes.field)&&r.evidence.some(e=>e.source?.file===n.source?.file));}
function contractDescription(contract:any):string[]{if(!contract||typeof contract!=='object')return [];const fields:string[]=[];for(const side of ['request','responses']as const){const values=side==='request'?[contract.request]:contract.responses||[];for(const item of values)if(item&&typeof item==='object'){const schema=(item as any).schema||item;const props=(schema as any).properties;if(props&&typeof props==='object')for(const [name,value]of Object.entries(props))fields.push(`${side==='request'?'請求':'回應'}欄位：${name}（${(value as any)?.type||'型別未提供'}）`);}}return fields;}
function componentDetail(panel:HTMLElement,index:Index,payload:Payload,screenId:string,componentId:string,label:string,onBack:()=>void,onFocus:(id:string)=>void,overrides?:{state:()=>ReviewState;change:(componentId:string,id:string)=>void}){const node=index.nodes.get(componentId)!;panel.replaceChildren(element('h2',label),element('p',`${kindName(node)} · ${resolution(index,node)}`));const back=element('button','返回畫面資訊');back.onclick=onBack;panel.append(back);panel.append(element('h3','動作'));const actions=actionSummary(index,componentId);for(const action of actions)panel.append(element('p',action));for(const b of (index.graph.behaviors||[]).filter(b=>b.triggerId===componentId)){if(b.type==='NAVIGATE'&&index.nodes.get(b.targetId||'')?.type==='SCREEN'){const target=index.nodes.get(b.targetId!)!,button=element('button',`前往畫面：${target.name}`);button.onclick=()=>onFocus(target.id);panel.append(button);}if(b.type==='CALL_API'&&index.nodes.get(b.targetId||'')?.type==='ENDPOINT'){const api=index.nodes.get(b.targetId!)!,button=element('button',`呼叫 API：${api.attributes.httpMethod||api.attributes.method||'ANY'} ${api.attributes.path||api.name}`);button.onclick=()=>apiDetail(panel,index,api.id,onBack,onFocus);panel.append(button);}}
 const rules=rulesFor(index,screenId,componentId);panel.append(element('h3','資料檢核'));for(const rule of rules)panel.append(element('p',`${rule.kind}：${rule.message||rule.fields.join('、')}（${rule.layer==='CLIENT'?'畫面檢核':rule.layer==='SERVER'?'伺服器檢核':'標記檢核'}）`));
 panel.append(element('h3','樣式'));const records=payload.preview.elements?.filter(e=>e.graphScreenId===screenId&&e.graphComponentId===componentId)||[];for(const record of records){const styles={...payload.preview.defaults?.[record.defaultId],...payload.preview.styles?.[record.styleId]};for(const [name,value]of Object.entries(styles))panel.append(element('p',`${name}：${value}`));}
 if(payload.componentLibrary)panel.append(libraryDetails(payload,componentId));if(overrides){const control=libraryOverride(payload,overrides.state(),screenId,componentId,value=>overrides.change(componentId,value));if(control)panel.append(control);}panel.append(element('p',`來源：${sourceText(node)}`));tech(panel,[{id:node.id,attributes:node.attributes,confidence:node.confidence,evidence:node.evidence,source:node.source},...((index.graph.behaviors||[]).filter(b=>b.triggerId===componentId))]);}

export function apiDetail(panel:HTMLElement,index:Index,id:string,onBack:()=>void,onCaller?:(screenId:string,componentId?:string)=>void){const node=index.nodes.get(id)!;panel.replaceChildren(element('h2','API 詳情'));const back=element('button','返回畫面資訊');back.onclick=onBack;panel.append(back);const method=node.attributes.httpMethod||node.attributes.method||'ANY',path=displayRoute(node.attributes.path||node.attributes.route||node.name);panel.append(element('h3','方法與路徑'),element('p',`${method} ${path}`));const handlers=(index.graph.relationships||[]).filter(e=>e.type==='HANDLED_BY'&&e.from===id).map(e=>index.nodes.get(e.to)).filter(Boolean);panel.append(element('h3','處理位置'));for(const handler of handlers)panel.append(element('p',`${handler!.name} · ${sourceText(handler)}`));const contracts=index.graph.apiContracts?.filter(c=>c.endpointId===id)||[];panel.append(element('h3','請求／回應契約'));for(const contract of contracts)for(const line of contractDescription(contract))panel.append(element('p',line));const usage=callSources(index.graph).get(id)||[];panel.append(element('h3','被哪些畫面或按鈕觸發'));for(const caller of usage){const behavior=index.graph.behaviors?.find(item=>item.id===caller.behaviorId),kind=callerKind(index,caller),edge=(index.graph.relationships||[]).find(item=>item.to===id&&item.from===(caller.componentId||caller.screenId)&&['CALLS','TRIGGERS'].includes(item.type)),buttonName=caller.componentId?index.nodes.get(caller.componentId)?.name:kind==='unresolved'?`未解析呼叫來源${behavior?.event?` · ${behavior.event}`:''}`:'畫面載入',button=element('button',`${index.nodes.get(caller.screenId)?.name||'畫面'} › ${buttonName||'可操作項目'}`);button.dataset.callerScreen=caller.screenId;if(caller.componentId)button.dataset.callerComponent=caller.componentId;button.onclick=()=>onCaller?.(caller.screenId,caller.componentId);const location=sourceText(behavior||edge||index.nodes.get(caller.componentId||caller.screenId));if(location!=='來源位置未提供')button.append(element('span',` · 來源：${location}`));panel.append(button);}tech(panel,[node.source,node.evidence,handlers.map(h=>({id:h!.id,attributes:h!.attributes,source:h!.source,evidence:h!.evidence})),contracts,index.graph.validationRules?.filter(r=>r.parameters?.endpointIds?.includes(id)||node.attributes.validationRuleIds?.includes(r.id)),usage]);}

export function behaviorDetail(panel:HTMLElement,index:Index,payload:Payload,screenId:string,b:Behavior,onBack:()=>void,onFocus:(id:string)=>void=()=>{}){panel.replaceChildren(element('h2',behaviorNames[b.type]||'操作詳情'));const back=element('button','返回畫面資訊');back.onclick=onBack;panel.append(back);const status=resolution(index,b);panel.append(element('p',`狀態：${status}`));if(b.event)panel.append(element('p',`操作時機：${b.event==='load'||b.event==='ready'?'畫面載入':b.event}`));if(b.guard||b.condition)panel.append(element('p',`條件：${b.guard||b.condition}`));const target=index.nodes.get(b.targetId||'');if(target?.type==='SCREEN'){const button=element('button',`目的畫面：${target.name}`);button.onclick=()=>onFocus(target.id);panel.append(button);}if(target?.type==='ENDPOINT'){const button=element('button',`呼叫 API：${target.attributes.httpMethod||target.attributes.method||'ANY'} ${target.attributes.path||target.name}`);button.onclick=()=>apiDetail(panel,index,target.id,onBack);panel.append(button);}const trigger=rootTrigger(index,b);for(const rule of rulesFor(index,screenId,trigger))panel.append(element('p',`資料檢核：${rule.kind} ${rule.message||rule.fields.join('、')}`));const unresolved=status==='未解析'||status==='有多個候選',candidates=unresolved?candidateNodes(index,b):[];if(unresolved)panel.append(element('p',status==='有多個候選'?'分析結果有多個可能目標，以下列出全部候選供確認。':'目前無法確認操作目標，請參考下方證據。'));if(candidates.length){panel.append(element('h3','所有候選'));for(const candidate of candidates){const readable=readableCandidate(candidate);panel.append(element('p',readable.length?readable.join(' · '):candidate.id,'candidate-readable'));}}tech(panel,[b.expression,b.evidence,(index.graph.behaviors||[]).filter(child=>child.parentId===b.id)],unresolved);}
export function elementDetail(panel:HTMLElement,payload:Payload,record:ElementRecord){panel.replaceChildren(element('h2','預覽元素樣式'),element('p',`${record.text||kindNames[record.tag.toUpperCase()]||'畫面元素'}`));const styles={...payload.preview.defaults?.[record.defaultId],...payload.preview.styles?.[record.styleId]};for(const [name,value]of Object.entries(styles))panel.append(element('p',`${name}：${value}`));for(const condition of record.conditions||[])panel.append(element('p',`顯示條件：${condition}`));panel.append(element('p',`來源：${record.source?`${record.source.file}:${record.source.line}`:'未提供'}`));tech(panel,[record]);}

export function screenPanel(panel:HTMLElement,index:Index,payload:Payload,id:string,onFocus:(id:string,component?:string)=>void,overrides?:{state:()=>ReviewState;change:(componentId:string,id:string)=>void},onSelectComponent?:(componentId:string)=>void){const screen=index.nodes.get(id)!,primary=index.routes.get(id)?.[0]?displayRoute(index.routes.get(id)![0]):'沒有已知 URL';panel.replaceChildren(element('h2',text.info));const summary=element('section',undefined,'screen-summary');summary.append(element('h3','畫面摘要'),element('p',`名稱：${screen.name}`),element('p',`主要 URL：${primary}`),element('p',`來源檔：${screen.source?.file||screen.attributes.view||'未提供'}`));panel.append(summary);
 const owners=[...index.owners].filter(([,screens])=>screens.includes(id)).map(([component])=>index.nodes.get(component)!).filter(Boolean),used=new Map<string,number>(),labels=new Map<string,string>();for(const node of owners){const base=componentLabel(node,owners.indexOf(node)+1),count=(used.get(base)||0)+1;used.set(base,count);const duplicate=owners.filter(candidate=>componentLabel(candidate,owners.indexOf(candidate)+1)===base).length>1;labels.set(node.id,duplicate?`${base}（${count}）`:base);}panel.append(element('h3','按鈕與可操作項目'));const actionSection=element('section',undefined,'action-items'),fieldSection=element('details',undefined,'field-items');fieldSection.append(element('summary','欄位與檢核'));for(const node of owners){const name=labels.get(node.id)!,entry=element('article',undefined,'action-item');entry.dataset.actionItem=node.id;const button=element('button',`${name} · ${kindName(node)}`);button.dataset.component=node.id;button.onclick=()=>{if(onSelectComponent)onSelectComponent(node.id);componentDetail(panel,index,payload,id,node.id,name,()=>screenPanel(panel,index,payload,id,onFocus,overrides,onSelectComponent),onFocus,overrides);};entry.append(button,element('span',resolution(index,node)));const actions=actionSummary(index,node.id);for(const action of actions)entry.append(element('p',`動作：${action}`));for(const behavior of screenBehaviors(index,id).filter(b=>rootTrigger(index,b)===node.id)){const detail=element('button',`${behaviorNames[behavior.type]||'操作詳情'}：查看內容`);detail.dataset.behavior=behavior.id;detail.onclick=()=>behaviorDetail(panel,index,payload,id,behavior,()=>screenPanel(panel,index,payload,id,onFocus,overrides,onSelectComponent),target=>onFocus(target));entry.append(detail);}(isAction(index,node)?actionSection:fieldSection).append(entry);}panel.append(actionSection,fieldSection);
 const calls=callSources(index.graph),groups=[['載入時呼叫','load'],['元件觸發','component'],['來源未解析','unresolved']]as const;for(const [title,type]of groups){const section=element('section',undefined,'api-call-group');section.append(element('h3',title));for(const [api,callers]of calls){const related=callers.filter(c=>c.screenId===id&&callerKind(index,c)===type);if(!related.length)continue;const endpoint=index.nodes.get(api)!,button=element('button',`${endpoint.attributes.httpMethod||endpoint.attributes.method||'ANY'} ${endpoint.attributes.path||endpoint.attributes.route||endpoint.name}`);button.dataset.api=api;button.onclick=()=>apiDetail(panel,index,api,()=>screenPanel(panel,index,payload,id,onFocus,overrides,onSelectComponent),onFocus);section.append(button,element('span',`呼叫來源 ${related.length} 次`));}panel.append(section);}
 const dialogs=screenBehaviors(index,id).filter(b=>b.type==='OPEN_DIALOG');panel.append(element('h3','彈窗'));for(const behavior of dialogs){const button=element('button',behavior.attributes?.title||'開啟彈窗');button.onclick=()=>behaviorDetail(panel,index,payload,id,behavior,()=>screenPanel(panel,index,payload,id,onFocus,overrides,onSelectComponent));panel.append(button);}
 const rules=new Map(rulesFor(index,id).map(rule=>[rule.id,rule]));for(const node of owners)for(const rule of rulesFor(index,id,node.id))rules.set(rule.id,rule);const validation=element('section');validation.classList.add('validation-rules');validation.append(element('h3','資料檢核'));for(const rule of rules.values())validation.append(element('p',`${rule.fields.map(field=>index.nodes.get(field)?.name||field).join('、')}：${rule.message||rule.kind}（${rule.layer==='CLIENT'?'畫面檢核':rule.layer==='SERVER'?'伺服器檢核':'標記檢核'}；${rule.layer}）`));panel.append(validation);
 const technical=[screen.source,screen.attributes,screen.confidence,screen.evidence,...owners.map(n=>({id:n.id,attributes:n.attributes,confidence:n.confidence,evidence:n.evidence})),...screenBehaviors(index,id),[...rules.values()]];for(const metadata of payload.preview.screens?.find(s=>s.graphScreenId===id)?.dynamicExpressions||[])technical.push(metadata);tech(panel,technical);}

export function unresolvedPanel(panel:HTMLElement,index:Index,payload:Payload,screenId:string,ids:string[],onBack:()=>void){panel.replaceChildren(element('h2',`未解析 ×${ids.length}`));const back=element('button','返回畫面資訊');back.onclick=onBack;panel.append(back);for(const id of ids){const behavior=index.behaviors.get(id);if(!behavior)continue;const trigger=rootTrigger(index,behavior),label=index.nodes.get(trigger||'')?.name||'畫面載入';const entry=element('section',undefined,'unresolved-item');behaviorDetail(entry,index,payload,screenId,behavior,onBack);entry.prepend(element('h3',label));panel.append(entry);}}
