import {inertDocument} from './inert-document';
import {iconSprite,icon,iconButton,segment,active,emptyPanel} from './shell-ui';
import {diagnosticsPanel} from './diagnostics';
import {partitionNavigation} from './overview';
import {componentLabel} from './labels';
import {screenNames,NameHint} from './names';
import {matchLibrary,libraryLabel} from './shared/library';
import {libraryDetails,libraryOverride} from './library-ui';
import {setOverride} from './shared/review';
import {Payload,requireGraph} from './contracts';
import {element,text} from './text';
import {indexGraph,searchScreens} from './map';
import {canvas,fileTree,CanvasTransform} from './canvas';
import {prototypeViewer,transition} from './prototype';
import {PrototypeHistory} from './prototype-history';
import {FocusRelation,focusBoardHeight,focusLayout,focusedRelations,relationTooltip} from './relations';
import {apiPage} from './api-page';
import {mdControls} from './md-controls';
import {screenPanel,elementDetail,apiDetail,unresolvedPanel} from './details';
import {previewDocument,previewElement,previewSelector} from './preview';
import {emptyReview,loadReview,saveReview,screenDecision,componentDecision,effectiveComponent,setScreen,setComponent,statistics,markableComponents,buttonComponents,conflicts,StorageLike} from './shared/review';
import {decisionControl,screenDecisionControl,decisionLabel} from './review-ui';
const root=document.querySelector<HTMLDivElement>('#app')!;

try {
 const payload=JSON.parse(document.querySelector('#st-data')!.textContent!) as Payload;
 const visibleTexts=new Map<string,Set<string>>();const remember=(id:string,node:Element|null)=>{if(!node||!['A','BUTTON'].includes(node.tagName))return;const value=node.textContent?.trim();if(!value||/\$\{|#\{|<%/.test(value))return;const values=visibleTexts.get(id)||new Set<string>();values.add(value);visibleTexts.set(id,values);};for(const [id,html]of Object.entries(payload.documents)){const doc=inertDocument(html);for(const node of doc.querySelectorAll('[data-st-component-id]'))remember(node.getAttribute('data-st-component-id')!,node);for(const record of payload.preview.elements||[])if(record.graphScreenId===id&&record.graphComponentId)try{remember(record.graphComponentId,doc.querySelector(previewSelector(record.path)));}catch{}}const visibleComponentText=(node:any)=>visibleTexts.get(node.id)?.size===1?[...visibleTexts.get(node.id)!][0]:undefined;const sourceGraph=requireGraph(payload.graph),sourceIndex=indexGraph(sourceGraph),hints=new Map<string,NameHint>();for(const screen of sourceIndex.screens){const document=inertDocument(payload.documents[screen.id]||'');hints.set(screen.id,{title:document.querySelector('title')?.textContent||undefined,heading:document.querySelector('h1')?.textContent||undefined});}const displayNames=screenNames(sourceIndex.screens,hints,sourceIndex.routes),graph={...sourceGraph,nodes:sourceGraph.nodes.map(node=>node.type==='SCREEN'?{...node,name:displayNames.get(node.id)||node.name}:node.type==='COMPONENT'?{...node,name:componentLabel({...node,displayLabel:visibleComponentText(node)}),displayLabel:visibleComponentText(node)}:node)},index=indexGraph(graph);
 document.querySelector('#application')!.textContent=graph.application.name;document.querySelector<HTMLElement>('#application')!.title=graph.application.name;
 const shell=element('div',undefined,'shell'),nav=element('nav'),main=element('main'),panel=element('aside'),topbar=document.querySelector('header')!;topbar.classList.add('topbar');document.body.prepend(iconSprite());shell.dataset.sidebarCollapsed=String(innerWidth<1024);shell.dataset.detailsOpen='false';
 nav.setAttribute('aria-label','畫面脈絡');emptyPanel(panel);const drawer=element('dialog',undefined,'information-drawer');drawer.setAttribute('aria-label','分析資訊');const drawerTitle=element('div',undefined,'drawer-heading'),closeDrawer=iconButton('關閉分析資訊','close');drawerTitle.append(element('h2','分析資訊'),closeDrawer);drawer.append(drawerTitle);closeDrawer.onclick=()=>drawer.close();drawer.addEventListener('click',event=>{if(event.target===drawer){const r=drawer.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)drawer.close();}});
 const libraryBox=element('details',undefined,'library-summary');libraryBox.dataset.librarySummary='true';libraryBox.append(element('summary','元件庫摘要'));if(payload.componentLibrary){const result=matchLibrary(graph,payload.componentLibrary);libraryBox.append(element('h3',libraryLabel(payload.componentLibrary)));for(const row of result.coverage)libraryBox.append(element('p',`${row.kind} 已對應 ${row.matched} 未對應 ${row.unmatched} 歧義 ${row.ambiguous}`));const technical=element('details');technical.append(element('summary','技術資訊'),element('p',payload.componentLibrary.sha256));libraryBox.append(technical);}else libraryBox.append(element('p','未匯入元件庫'));
 const screens=element('button',text.screens),apis=element('button',text.apis),overview=element('button','地圖'),files=element('button',text.files),search=element('input');
 search.type='text';search.setAttribute('aria-label',text.search);search.placeholder=text.search;const primary=segment([screens,apis],'主要導覽');screens.prepend(icon('screen'));apis.prepend(icon('api'));topbar.append(primary);active([screens,apis],screens);const searchBox=element('div',undefined,'search-box'),clearSearch=iconButton('清除搜尋','close');searchBox.append(icon('search'),search,clearSearch);const collapse=iconButton('收合畫面清單','back');nav.append(collapse,searchBox,segment([overview,files],'畫面檢視'));active([overview,files],overview);if(innerWidth<1024)collapse.setAttribute('aria-label','展開畫面清單');collapse.onclick=()=>{const collapsed=shell.dataset.sidebarCollapsed!=='true';shell.dataset.sidebarCollapsed=String(collapsed);collapse.setAttribute('aria-label',collapsed?'展開畫面清單':'收合畫面清單');collapse.title=collapse.getAttribute('aria-label')!;};
 const diagnostics=[...(graph.diagnostics||[]),...(payload.preview.diagnostics||[]),...(Array.isArray(payload.manifest.diagnostics)?payload.manifest.diagnostics:[])];if(diagnostics.length)drawer.append(diagnosticsPanel(diagnostics));const information=element('button',`分析資訊 ${diagnostics.length}`,'secondary');information.prepend(icon('info'));information.onclick=()=>drawer.showModal();drawer.addEventListener('close',()=>information.focus());const detailToggle=element('button','查看資訊','secondary details-toggle');detailToggle.setAttribute('aria-label','查看選取物件資訊');detailToggle.setAttribute('aria-expanded','false');const setDetails=(open:boolean)=>{shell.dataset.detailsOpen=String(open);detailToggle.setAttribute('aria-expanded',String(open));detailToggle.textContent=open?'關閉資訊':'查看資訊';detailToggle.setAttribute('aria-label',open?'關閉選取物件資訊':'查看選取物件資訊');};detailToggle.onclick=()=>setDetails(shell.dataset.detailsOpen!=='true');topbar.append(detailToggle);
 let apiView=false;let mode='overview',current:string|undefined,showGlobal=false;const history:string[]=[];const prototypeHistory=new PrototypeHistory();let flowView=false,canvasTransform:CanvasTransform|undefined;const prototypeScroll=()=>main.querySelector<HTMLElement>('.prototype-scroll')?.scrollTop||0;const movePrototype=(delta:number)=>{const visit=prototypeHistory.move(delta,prototypeScroll());if(visit)focus(visit.screenId,undefined,false);};
 const prototypeKey=(event:KeyboardEvent)=>{if(drawer.open||!current)return;const editable=(event.target as Element)?.closest?.('input,textarea,select,[contenteditable]');if(event.key==='Escape'){event.preventDefault();show();}else if(event.altKey&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();movePrototype(event.key==='ArrowLeft'?-1:1);}else if(!editable&&['+','-','='].includes(event.key)){event.preventDefault();const zoom=main.querySelector<HTMLSelectElement>('[aria-label="原型縮放"]');if(zoom){const value=Number(main.querySelector<HTMLElement>('.prototype-viewer')?.dataset.scale||'1'),levels=[.5,.75,1],next=event.key==='-'?[...levels].reverse().find(v=>v<value):levels.find(v=>v>value);const selected=next??(event.key==='-'?.5:1);zoom.value=[...zoom.options].find(option=>Number(option.value)===selected)?.value||'fit';zoom.dispatchEvent(new Event('change'));}}};
 let storage:StorageLike|undefined;try{storage=window.localStorage;}catch{}const restored=loadReview(storage,graph,payload.fingerprint,payload.componentLibrary);let reviewState=restored.state,review=false;
 const orphanBox=element('section',undefined,'library-orphans');drawer.append(orphanBox);
 const warning=element('p',restored.warning,'storage-warning'),stats=element('div',undefined,'review-statistics'),conflictList=element('div',undefined,'conflicts');nav.append(warning,stats,conflictList);
 const toggleLabel=element('label',text.review),toggle=element('input');toggle.type='checkbox';toggle.setAttribute('aria-label',text.review);toggleLabel.prepend(toggle);toggleLabel.classList.add('toggle-switch');topbar.append(toggleLabel);
 const filter=element('select');filter.setAttribute('aria-label',text.stateFilter);for(const value of ['ALL','UNDECIDED','KEEP','REMOVE','INHERITED_REMOVE']){const option=element('option',value==='ALL'?text.all:decisionLabel(value as 'KEEP'));option.value=value;filter.append(option);}const chips=element('div',undefined,'state-chips'),screenList=element('div',undefined,'sidebar-screens');chips.setAttribute('role','group');chips.setAttribute('aria-label',text.stateFilter);nav.append(chips,screenList);
 const summaries=()=>{orphanBox.replaceChildren();for(const orphan of reviewState.orphan_component_overrides||[])orphanBox.append(element('p',`舊覆寫：${orphan.screenId}／${orphan.componentId}／${orphan.libraryComponentId}`));stats.hidden=conflictList.hidden=chips.hidden=!review;const counts=statistics(graph,reviewState);stats.replaceChildren(element('h3',text.statistics));for(const [label,values]of [[text.screens,counts.screens],['按鈕',counts.components]]as const)stats.append(element('p',`${label} ${text.undecided}: ${values.UNDECIDED} ${text.keep}: ${values.KEEP} ${text.remove}: ${values.REMOVE}`));const inheritedFilter=element('button',`${text.inherited}: ${counts.inherited}`,'inherited-filter');inheritedFilter.setAttribute('aria-pressed',String(filter.value==='INHERITED_REMOVE'));inheritedFilter.onclick=()=>{filter.value='INHERITED_REMOVE';summaries();if(current)focus(current);else show();};stats.append(inheritedFilter);for(const [label,values]of [[text.screens,counts.screens],['按鈕',counts.components]]as const){const bar=element('div',undefined,'statistics-bar');bar.setAttribute('aria-label',`${label}比例`);const total=values.KEEP+values.REMOVE+values.UNDECIDED;for(const value of ['KEEP','REMOVE','UNDECIDED']as const){const slice=element('span');slice.className=`decision-${value}`;slice.style.width=`${total?values[value]/total*100:0}%`;slice.title=`${decisionLabel(value)} ${values[value]}`;bar.append(slice);}stats.append(bar);}chips.replaceChildren();for(const value of ['ALL','UNDECIDED','KEEP','REMOVE']){const count=value==='ALL'?index.screens.length:counts.screens[value as 'KEEP'];const button=element('button',`${value==='ALL'?text.all:decisionLabel(value as 'KEEP')} ${count}`,'chip');button.dataset.stateFilter=value;button.setAttribute('aria-pressed',String(filter.value===value));button.onclick=()=>{filter.value=value;summaries();if(current)focus(current);else show();};chips.append(button);}updateScreenList();const currentConflicts=conflicts(graph,reviewState);conflictList.hidden=!review||!currentConflicts.length;conflictList.replaceChildren(element('h3',text.conflicts));for(const c of currentConflicts)conflictList.append(element('p',`${index.nodes.get(c.screenId)?.name}: ${index.nodes.get(c.componentId)?.name} → ${index.nodes.get(c.targetScreenId)?.name}`));};
 const changed=()=>{const failure=saveReview(storage,reviewState);if(failure)warning.textContent=failure;summaries();if(current)focus(current);else if(apiView)showApi();else show();};
 const md=mdControls(payload,()=>reviewState,state=>{reviewState=state;changed();});topbar.append(md,information);drawer.append(libraryBox);root.after(drawer);
 const badge=(decision:string)=>{const mark=element('span',decisionLabel(decision as 'KEEP'),'review-status-badge');mark.dataset.reviewStatus=decision;mark.classList.add(`decision-${decision}`);return mark;};
 const decorate=(id:string,parent:HTMLElement)=>{const decision=screenDecision(reviewState,id);parent.append(screenDecisionControl(text.screenDecision,decision,value=>{reviewState=setScreen(reviewState,id,value);changed();},id));};
 const focus=(id:string,component?:string,push=true,animateCard=false)=>{
  const from=animateCard?main.querySelector<HTMLElement>(`.screen-card[data-screen="${CSS.escape(id)}"]`)?.getBoundingClientRect():undefined;if(!current)prototypeHistory.start(id);else if(push||current===id&&main.querySelector('.prototype-viewer'))prototypeHistory.visit(id,prototypeScroll());else if(prototypeHistory.current?.screenId!==id)prototypeHistory.restore(id,prototypeScroll());history.splice(0,history.length,...prototypeHistory.trail);
  if(current!==id||apiView)setDetails(false);current=id;apiView=false;if(innerWidth<1024){shell.dataset.sidebarCollapsed='true';collapse.setAttribute('aria-label','展開畫面清單');}shell.dataset.page='screen';active([screens,apis],screens);updateScreenList();
  const screen=index.nodes.get(id)!;const heading=element('div',undefined,'focus-heading'),back=iconButton(text.back,'back');back.disabled=!history.length;back.onclick=()=>{const previous=history.pop();if(previous)focus(previous,undefined,false);};const breadcrumbs=element('div',undefined,'focus-breadcrumb');breadcrumbs.setAttribute('aria-label','畫面瀏覽路徑');const home=element('button','總覽');home.onclick=()=>{history.length=0;show();};breadcrumbs.append(home);for(const [offset,visited]of history.entries()){const crumb=element('button',index.nodes.get(visited)?.name||text.noUrl);crumb.onclick=()=>{history.splice(offset);focus(visited,undefined,false);};breadcrumbs.append(element('span','／'),crumb);}breadcrumbs.append(element('span','／'),element('h2',screen.name));heading.append(back,breadcrumbs);main.replaceChildren(heading);if(review)decorate(id,heading);
  const metadata=payload.preview.screens?.find(s=>s.graphScreenId===id);
  if(metadata?.rendering?.mode==='skipped')main.append(element('p',metadata.rendering.diagnostic||text.noPreview));
  const preview=element('section',undefined,'preview'),loading=element('div','載入預覽…','preview-loading');loading.setAttribute('role','status');preview.setAttribute('aria-busy','true');const thumbnail=metadata?.thumbnail;if(thumbnail?.startsWith('data:image/')){const image=element('img');image.src=thumbnail;image.alt='預覽縮圖';loading.prepend(image);}const frame=element('iframe');frame.style.visibility='hidden';frame.setAttribute('sandbox','allow-same-origin');frame.title=screen.name;
  frame.onload=()=>{const document=frame.contentDocument;if(!document||!frame.getAttribute('srcdoc'))return;document.addEventListener('keydown',prototypeKey);loading.hidden=true;frame.style.visibility='';preview.setAttribute('aria-busy','false');document.addEventListener('submit',e=>{e.preventDefault();const status=main.querySelector('.prototype-status');if(status)status.textContent='靜態分析無法確認這個操作（模擬送出尚未啟用）';},true);document.addEventListener('click',e=>{e.preventDefault();const status=main.querySelector('.prototype-status');if(status){const target=(e.target as Element)?.closest?.('a,button,input[type=submit]');if(target)status.textContent=target.tagName==='A'&&/^(https?:)?\/\//i.test(target.getAttribute('href')||'')?'外部連結（不會開啟）':'靜態分析無法確認這個操作（模擬尚未啟用）';}const node=e.target;if(!node||!(node as Element).tagName)return;const record=previewElement(payload,id,node as Element);document.querySelectorAll<HTMLElement>('[data-prototype-selected]').forEach(n=>{n.removeAttribute('data-prototype-selected');n.style.outline=n.dataset.prototypeOutline||'';delete n.dataset.prototypeOutline;});(node as HTMLElement).dataset.prototypeOutline=(node as HTMLElement).style.outline;(node as HTMLElement).dataset.prototypeSelected='true';(node as HTMLElement).style.outline='3px solid #eab308';if(record){setDetails(true);elementDetail(panel,payload,record);if(record.graphComponentId){panel.append(libraryDetails(payload,record.graphComponentId));if(review&&buttonComponents(graph).some(key=>key.screenId===id&&key.componentId===record.graphComponentId)){panel.append(decisionControl(index.nodes.get(record.graphComponentId)?.name||'可操作項目',componentDecision(reviewState,id,record.graphComponentId),value=>{reviewState=setComponent(reviewState,id,record.graphComponentId!,value);changed();},id,record.graphComponentId));panel.append(badge(componentDecision(reviewState,id,record.graphComponentId)));}}}});

   if(component){const nodes=new Set<Element>([...document.querySelectorAll(`[data-st-component-id="${CSS.escape(component)}"]`)]);for(const record of payload.preview.elements||[])if(record.graphScreenId===id&&record.graphComponentId===component)try{const node=document.querySelector(previewSelector(record.path));if(node)nodes.add(node);}catch{}for(const node of nodes){(node as HTMLElement).style.outline='3px solid #eab308';}nodes.values().next().value?.scrollIntoView({block:'center'});}

  };
  frame.srcdoc=previewDocument(payload,id,document=>{if(review)for(const record of payload.preview.elements||[])if(record.graphScreenId===id&&record.graphComponentId){let node:HTMLElement|null;try{node=document.querySelector(previewSelector(record.path));}catch{continue;}if(!node)continue;const decision=componentDecision(reviewState,id,record.graphComponentId),color=decision==='KEEP'?'#15803d':decision==='REMOVE'?'#b91c1c':'#64748b';node.dataset.reviewStatus=decision;node.style.outline=`3px solid ${color}`;const label=decisionLabel(decision),badge=document.createElement('span');badge.dataset.reviewBadge=record.graphComponentId;badge.textContent=label;badge.style.cssText=`display:inline-block;background:${color};color:white;font:600 11px system-ui;padding:2px 5px;border-radius:4px;pointer-events:none;`;if(node.tagName.toLowerCase()==='input')node.insertAdjacentElement('afterend',badge);else node.append(badge);}});const notice=element('span','示意','preview-notice');notice.title='動態資料為範例值';preview.append(frame,loading,notice);
  const allRelations=focusedRelations(index,id),parts=partitionNavigation(index),globalRelations=parts.global.filter(r=>r.from===id),relations:FocusRelation[]=[...parts.flows.filter(r=>r.from===id),...allRelations.filter(r=>r.unresolved)],points=focusLayout(relations.length),height=focusBoardHeight(relations.length),board=element('section',undefined,'focus-graph');board.setAttribute('aria-label',text.related);board.style.height=`${height}px`;
  if(!relations.length)board.append(element('p',globalRelations.length?'沒有畫面特有流程；全站導覽見下方':text.noDestinations,'no-destinations'));
  const center=element('div',undefined,'focus-center');center.style.left='380px';center.style.top=`${height/2-75}px`;center.append(element('strong',screen.name));const primary=element('span',index.routes.get(id)?.[0]||text.noUrl);primary.title=(index.routes.get(id)||[]).join('\n');center.append(primary);center.append(preview);
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 1000 ${height}`);svg.classList.add('focus-relation-lines');const defs=document.createElementNS(svg.namespaceURI,'defs'),marker=document.createElementNS(svg.namespaceURI,'marker'),arrow=document.createElementNS(svg.namespaceURI,'path');marker.setAttribute('id','focus-arrow');marker.setAttribute('viewBox','0 0 6 6');marker.setAttribute('refX','6');marker.setAttribute('refY','3');marker.setAttribute('markerWidth','6');marker.setAttribute('markerHeight','6');marker.setAttribute('orient','auto');arrow.setAttribute('d','M0,0 L6,3 L0,6 Z');arrow.setAttribute('fill','#94aab4');marker.append(arrow);defs.append(marker);svg.append(defs);const centerY=height/2;
  for(let i=0;i<relations.length;i++){const r=relations[i],point=points[i],target=index.nodes.get(r.to),name=target?.name||(r.unresolved?`${text.unresolved} ×${r.behaviorIds.length}`:text.unresolved),card=element('button',undefined,'focus-destination');card.dataset.destination=r.to;card.dataset.relationTo=r.to;card.classList.toggle('unresolved-destination',!!r.unresolved);card.style.left=`${point.x}px`;card.style.top=`${point.y}px`;card.append(element('strong',name));if(r.unresolved)card.append(element('span',text.unresolved));else {const route=index.routes.get(r.to)?.[0],routeLabel=element('span',route||text.noUrl);routeLabel.title=(index.routes.get(r.to)||[]).join('\n');card.append(routeLabel);const thumbnail=payload.preview.screens?.find(s=>s.graphScreenId===r.to)?.thumbnail;if(thumbnail?.startsWith('data:image/')){const img=element('img');img.src=thumbnail;img.alt=name;card.append(img);}}const tooltip=relationTooltip(index,payload,r);tooltip.hidden=true;tooltip.classList.add('focus-tooltip');tooltip.style.left=`${point.x}px`;tooltip.style.top=`${point.y+96}px`;const showTip=()=>{tooltip.hidden=false;board.querySelectorAll('.focus-relation-visible').forEach(line=>{line.classList.toggle('is-highlighted',line===path);line.classList.toggle('is-muted',line!==path);});board.querySelectorAll('.focus-destination').forEach(destination=>{destination.classList.toggle('is-highlighted',destination===card);destination.classList.toggle('is-muted',destination!==card);});center.classList.add('is-highlighted');},hideTip=()=>{tooltip.hidden=true;board.querySelectorAll('.focus-relation-visible,.focus-destination,.focus-center').forEach(node=>node.classList.remove('is-highlighted','is-muted'));};card.onmouseenter=card.onfocus=showTip;card.onmouseleave=card.onblur=hideTip;if(!r.unresolved)card.onclick=()=>focus(r.to);else card.onclick=()=>{setDetails(true);unresolvedPanel(panel,index,payload,id,r.behaviorIds,()=>focus(id));};
   const path=document.createElementNS(svg.namespaceURI,'path'),hit=document.createElementNS(svg.namespaceURI,'path');let sx=500,sy=centerY,ex=point.x+95,ey=point.y+48;if(point.side==='left'){sx=380;sy=centerY;}else if(point.side==='right'){sx=620;sy=centerY;}else if(point.side==='top'){sx=500;sy=centerY;}else{sx=500;sy=centerY;}if(point.side==='left')ex=point.x+190;else if(point.side==='right')ex=point.x;else if(point.side==='top')ey=point.y+105;else ey=point.y;if(r.to===id){const d=`M620 ${centerY-35} C760 ${centerY-130} 760 ${centerY+130} 620 ${centerY+35}`;path.setAttribute('d',d);hit.setAttribute('d',d);}else {const d=`M${sx} ${sy} C${(sx+ex)/2} ${sy} ${(sx+ex)/2} ${ey} ${ex} ${ey}`;path.setAttribute('d',d);hit.setAttribute('d',d);}path.setAttribute('marker-end','url(#focus-arrow)');path.setAttribute('class',`focus-relation-visible${r.unresolved?' unresolved':''}`);hit.setAttribute('class','focus-relation');hit.setAttribute('tabindex','0');hit.setAttribute('role','button');hit.setAttribute('aria-label',`${name}${r.unresolved?'，'+text.unresolved:''}`);const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=name;hit.append(title);hit.addEventListener('mouseenter',showTip);hit.addEventListener('mouseleave',hideTip);hit.addEventListener('focus',showTip);hit.addEventListener('blur',hideTip);if(!r.unresolved){hit.addEventListener('click',()=>focus(r.to));hit.addEventListener('keydown',event=>{if((event as KeyboardEvent).key==='Enter'||(event as KeyboardEvent).key===' '){event.preventDefault();focus(r.to);}});}svg.append(path,hit);board.append(card,tooltip);
  }
  board.append(svg,center);const world=element('div',undefined,'focus-world');world.style.width='1000px';world.style.height=`${height}px`;world.append(...board.childNodes);board.append(world);main.append(board);const fit=()=>{if(!board.isConnected){resize.disconnect();return;}const available=Math.max(240,main.clientHeight-heading.offsetHeight-48),scale=Math.min(1,(board.clientWidth-24)/1000,available/height);world.style.transform=`translate(${(board.clientWidth-1000*scale)/2}px,12px) scale(${scale})`;board.style.height=`${height*scale+24}px`;};const resize=new ResizeObserver(fit);resize.observe(main);requestAnimationFrame(fit);if(globalRelations.length){const group=element('section',undefined,'global-navigation');group.append(element('h3',`全站導覽（${globalRelations.length} 個目的）`));for(const r of globalRelations){const button=element('button',index.nodes.get(r.to)?.name||text.noUrl);button.dataset.destination=r.to;button.dataset.relationTo=r.to;button.append(element('span',(index.routes.get(r.to)||[])[0]||text.noUrl));button.onclick=()=>focus(r.to);const tip=relationTooltip(index,payload,r);tip.hidden=true;button.onmouseenter=button.onfocus=()=>{tip.hidden=false;};button.onmouseleave=button.onblur=()=>{tip.hidden=true;};group.append(button,tip);}main.append(group);}
  if(flowView){const full=element('button','查看完整畫面');full.onclick=()=>{flowView=false;focus(id,undefined,false);};center.prepend(full);}else{const viewer=prototypeViewer(index,payload,id,preview,frame,prototypeHistory,{back:()=>show(),focus:target=>focus(target),flow:()=>{flowView=true;focus(id,undefined,false);},move:movePrototype,reset:()=>{const visit=prototypeHistory.reset();if(visit)focus(visit.screenId,undefined,false);},scroll:prototypeHistory.current?.scroll||0});main.replaceChildren(viewer);if(review)decorate(id,viewer.querySelector('.prototype-toolbar')!);viewer.dataset.transition='complete';if(from&&!matchMedia('(prefers-reduced-motion: reduce)').matches){viewer.dataset.transition='running';preview.style.opacity='0';frame.style.pointerEvents='none';transition(metadata?.thumbnail,screen.name,from,main.getBoundingClientRect(),()=>{preview.style.opacity='';frame.style.pointerEvents='';viewer.dataset.transition='complete';});}}
  screenPanel(panel,index,payload,id,focus,review&&payload.componentLibrary?{state:()=>reviewState,change:(componentId,value)=>{reviewState=setOverride(reviewState,graph,payload.componentLibrary!,id,componentId,value);changed();}}:undefined,componentId=>focus(id,componentId));if(review){const section=element('section',undefined,'component-decisions');section.append(element('h3','按鈕確認'));for(const [decision,label]of [['KEEP','此畫面所有按鈕標為保留'],['REMOVE','此畫面所有按鈕標為移除'],['UNDECIDED','此畫面所有按鈕標為未確認']]as const){const action=element('button',label);action.dataset.batchDecision=decision;action.onclick=()=>{for(const key of buttonComponents(graph).filter(k=>k.screenId===id))reviewState=setComponent(reviewState,id,key.componentId,decision);changed();};section.append(action);}for(const key of markableComponents(graph).filter(k=>k.screenId===id)){
  const node=index.nodes.get(key.componentId)!;const attrs=node.attributes,kind=String(attrs.kind||'').toUpperCase(),tag=String(attrs.tag||'').toLowerCase(),inputType=String(attrs.type||attrs.inputType||'').toLowerCase();if(!(['BUTTON','LINK','SUBMIT'].includes(kind)||tag==='a'||['button','html:button','html:submit','html:cancel','html:image'].includes(tag)||tag==='input'&&['button','submit','image'].includes(inputType)))continue;const effective=effectiveComponent(reviewState,id,key.componentId);if(filter.value!=='ALL'&&effective!==filter.value)continue;const entry=element('div',undefined,'component-review');entry.append(decisionControl(index.nodes.get(key.componentId)!.name,componentDecision(reviewState,id,key.componentId),value=>{reviewState=setComponent(reviewState,id,key.componentId,value);changed();},undefined,key.componentId));if(effective==='INHERITED_REMOVE')entry.append(element('span',text.inherited));const row=panel.querySelector<HTMLElement>(`[data-action-item="${CSS.escape(key.componentId)}"]`);if(row){row.classList.add('component-review');row.append(...entry.childNodes);}else section.append(entry);}const actions=panel.querySelector<HTMLElement>('[data-detail-tab="0"]')!;actions.classList.add('component-decisions');actions.prepend(section);}if(review&&payload.componentLibrary){const section=element('section');section.append(element('h3','元件庫覆寫'));for(const [componentId,owners]of index.owners)if(owners.includes(id)){const control=libraryOverride(payload,reviewState,id,componentId,value=>{reviewState=setOverride(reviewState,graph,payload.componentLibrary!,id,componentId,value);changed();});if(control)section.append(control);}(panel.querySelector('[data-detail-tab="0"]')||panel).append(section);}summaries();
 };
 const updateScreenList=()=>{screenList.replaceChildren();if(mode==='files'){screenList.append(fileTree(index,search.value,focus,{decorate:review?decorate:undefined,visible:review&&filter.value!=='ALL'?new Set(index.screens.filter(s=>screenDecision(reviewState,s.id)===filter.value).map(s=>s.id)):undefined}));return;}const matches=searchScreens(index,search.value);for(const screen of index.screens){if(!matches.has(screen.id)||review&&filter.value!=='ALL'&&screenDecision(reviewState,screen.id)!==filter.value)continue;const row=element('button',undefined,'sidebar-screen');row.dataset.screenList=screen.id;row.setAttribute('aria-current',current===screen.id?'page':'false');const statusIcon=icon(screenDecision(reviewState,screen.id)==='KEEP'?'check':screenDecision(reviewState,screen.id)==='REMOVE'?'close':'question');statusIcon.classList.add(`decision-${screenDecision(reviewState,screen.id)}`);const route=element('span',index.routes.get(screen.id)?.[0]||text.noUrl);route.title=route.textContent||'';row.setAttribute('aria-label',`${screen.name}，${route.textContent}，${review?decisionLabel(screenDecision(reviewState,screen.id)):''}`);if(review)row.append(statusIcon);row.classList.toggle('has-status',review);row.append(element('strong',screen.name),route);row.onclick=()=>focus(screen.id);screenList.append(row);}};
 const show=()=>{const previous=current,from=main.querySelector('.prototype-viewer')?.getBoundingClientRect();flowView=false;apiView=false;shell.dataset.page='screen';current=undefined;setDetails(false);updateScreenList();const options={transform:canvasTransform,onTransformChange:(state:CanvasTransform)=>{canvasTransform=state;},showGlobal,onGlobalChange:(value:boolean)=>{showGlobal=value;},visible:review&&filter.value!=='ALL'?new Set(index.screens.filter(s=>screenDecision(reviewState,s.id)===filter.value).map(s=>s.id)):undefined,decorate:review?decorate:undefined,screenStatus:review?(id:string)=>screenDecision(reviewState,id):undefined};main.replaceChildren(canvas(index,payload,search.value,id=>focus(id,undefined,true,true),options));emptyPanel(panel);if(previous&&from){const card=main.querySelector<HTMLElement>(`.screen-card[data-screen="${CSS.escape(previous)}"]`);if(card)transition(payload.preview.screens?.find(s=>s.graphScreenId===previous)?.thumbnail,index.nodes.get(previous)!.name,from,card.getBoundingClientRect(),()=>{});}};
 const showApi=()=>{apiView=true;shell.dataset.page='api';current=undefined;active([screens,apis],apis);updateScreenList();main.replaceChildren(apiPage(index,reviewState,id=>{setDetails(true);apiDetail(panel,index,id,()=>{emptyPanel(panel,'api');setDetails(false);},focus,reviewState);},(screenId,componentId)=>focus(screenId,componentId),sourceIndex));setDetails(false);emptyPanel(panel,'api');};apis.onclick=showApi;
 overview.onclick=()=>{mode='overview';active([overview,files],overview);active([screens,apis],screens);show();};files.onclick=()=>{mode='files';active([overview,files],files);active([screens,apis],screens);show();};screens.onclick=()=>{active([screens,apis],screens);show();};search.oninput=()=>{active([screens,apis],screens);show();};clearSearch.onclick=()=>{search.value='';active([screens,apis],screens);show();search.focus();};toggle.onchange=()=>{review=toggle.checked;summaries();if(current)focus(current);else if(apiView)showApi();else show();};filter.onchange=()=>{if(current)focus(current);else show();};
 document.addEventListener('keydown',event=>{if(current&&!drawer.open){prototypeKey(event);if(event.defaultPrevented)return;}if(event.key==='/'&&!drawer.open&&!(event.target as Element)?.closest('input,textarea,select,[contenteditable]')){event.preventDefault();if(apiView){main.querySelector<HTMLInputElement>('.api-toolbar input')?.focus();}else{shell.dataset.sidebarCollapsed='false';collapse.setAttribute('aria-label','收合畫面清單');search.focus();}}else if(event.key==='Escape'&&!drawer.open&&innerWidth<1280&&shell.dataset.detailsOpen==='true'){setDetails(false);detailToggle.focus();}else if(event.key==='Escape'&&!drawer.open&&current){const previous=history.pop();if(previous)focus(previous,undefined,false);else show();}});
 summaries();show();shell.append(nav,main,panel);root.replaceChildren(shell);root.dataset.ready='true';
} catch(error){root.replaceChildren(element('p',String(error)));root.dataset.error='true';}
