import {Payload} from './contracts';import {ReviewState} from './shared/review';
import {generateMarkdown,importMarkdown,markdownSizeWarning} from './shared/review-md';
import {element,text} from './text';
/** Reads only an explicitly selected local file; imported prose never becomes HTML. */
export function mdControls(payload:Payload,current:()=>ReviewState,apply:(state:ReviewState)=>void):HTMLElement {
 const section=element('section',undefined,'md-controls'),exportButton=element('button',text.exportMd),label=element('label',text.importMd),input=element('input'),status=element('p'),orphans=element('div');
 input.type='file';input.accept='.md,text/markdown,text/plain';input.setAttribute('aria-label',text.importMd);status.dataset.mdStatus='';status.setAttribute('role','status');orphans.dataset.mdOrphans='';label.append(input);section.append(exportButton,label,status,orphans);
 exportButton.onclick=async()=>{exportButton.disabled=true;try{const md=await generateMarkdown(payload,current());const blob=new Blob([md],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),link=element('a');link.href=url;link.download='screentrace-review.md';link.hidden=true;section.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent=markdownSizeWarning(md)?text.largeMd:text.exportComplete;}catch(error){status.textContent=`${text.exportFailed}：${String(error)}`;}finally{exportButton.disabled=false;}};
 let revision=0;input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const token=++revision;section.setAttribute('aria-busy','true');try{if(file.size>1_073_741_824)throw Error(text.importSize);const imported=await importMarkdown(await file.text(),payload);if(token!==revision)return;apply(imported.state);orphans.replaceChildren();if(imported.orphans.length){orphans.append(element('h3',text.orphans));for(const orphan of imported.orphans)orphans.append(element('p',`${orphan.screenId}${orphan.componentId?' / '+orphan.componentId:''}`));}status.textContent=imported.changed?`${text.importComplete}；${text.analysisChanged}`:text.importComplete;}catch(error){if(token===revision)status.textContent=`${text.importFailed}：${String(error)}`;}finally{if(token===revision){section.removeAttribute('aria-busy');input.value='';}}};return section;
}
