import {Payload} from './contracts';import {ReviewState} from './shared/review';
import {generateMarkdown,importMarkdown,markdownSizeWarning} from './shared/review-md';
import {buttonComponents,conflicts,screenDecision,statistics} from './shared/review';
import {indexGraph} from './map';
import {element,text} from './text';
/** Reads only an explicitly selected local file; imported prose never becomes HTML. */
export function mdControls(payload:Payload,current:()=>ReviewState,apply:(state:ReviewState)=>void):HTMLElement {
 const section=element('section',undefined,'md-controls'),exportButton=element('button',text.exportMd),label=element('button',text.importMd,'secondary'),input=element('input'),status=element('p'),orphans=element('div'),dialog=element('dialog',undefined,'pre-export-check');dialog.setAttribute('aria-label','匯出前檢查');exportButton.dataset.mdExport='true';label.dataset.mdImport='true';label.setAttribute('role','menuitem');
 input.type='file';input.accept='.md,text/markdown,text/plain';input.setAttribute('aria-label',text.importMd);status.dataset.mdStatus='';status.setAttribute('role','status');orphans.dataset.mdOrphans='';input.hidden=true;label.onclick=()=>input.click();exportButton.className='primary';section.append(exportButton,label,input,status,orphans);document.body.append(dialog);
 const exportNow=async()=>{exportButton.disabled=true;try{const md=await generateMarkdown(payload,current());const blob=new Blob([md],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),link=element('a');link.href=url;link.download='screentrace-review.md';link.hidden=true;section.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent=markdownSizeWarning(md)?text.largeMd:text.exportComplete;}catch(error){status.textContent=`${text.exportFailed}：${String(error)}`;}finally{exportButton.disabled=false;}};
 const preferences=()=>{try{return JSON.parse(window.localStorage.getItem('screentrace:confirmation-preferences:v1')||'{}') as {skipExportCheck?:boolean};}catch{return {};}};
 const showExportCheck=()=>{const state=current(),counts=statistics(payload.graph,state),index=indexGraph(payload.graph),removedScreens=payload.graph.nodes.filter(node=>node.type==='SCREEN'&&screenDecision(state,node.id)==='REMOVE'),removedComponents=buttonComponents(payload.graph).filter(key=>state.componentDecisions[key.screenId]?.[key.componentId]==='REMOVE'),pendingScreens=payload.graph.nodes.filter(node=>node.type==='SCREEN'&&screenDecision(state,node.id)==='UNDECIDED'),pendingComponents=buttonComponents(payload.graph).filter(key=>!state.componentDecisions[key.screenId]?.[key.componentId]||state.componentDecisions[key.screenId][key.componentId]==='UNDECIDED'),issues=conflicts(payload.graph,state);
  dialog.replaceChildren(element('h2','匯出前檢查'),element('p',`畫面：保留 ${counts.screens.KEEP} · 移除 ${counts.screens.REMOVE} · 未確認 ${counts.screens.UNDECIDED}`),element('p',`按鈕：保留 ${counts.components.KEEP} · 移除 ${counts.components.REMOVE} · 未確認 ${counts.components.UNDECIDED}`),element('h3',`移除清單：${removedScreens.length} 個畫面、${removedComponents.length} 個按鈕`));
  const removed=element('ul',undefined,'pre-export-removed');for(const node of removedScreens)removed.append(element('li',`畫面：${node.name}`));for(const key of removedComponents)removed.append(element('li',`按鈕：${index.nodes.get(key.componentId)?.name||'可操作項目'}（${index.nodes.get(key.screenId)?.name||'畫面'}）`));dialog.append(removedScreens.length||removedComponents.length?removed:element('p','目前沒有移除項目'));
  dialog.append(element('h3',`仍有衝突：${issues.length} 個`));if(issues.length){const list=element('ul','', 'pre-export-conflicts');for(const issue of issues)list.append(element('li',`${index.nodes.get(issue.screenId)?.name||'畫面'} 的「${index.nodes.get(issue.componentId)?.name||'按鈕'}」仍指向已移除畫面「${index.nodes.get(issue.targetScreenId)?.name||'畫面'}」`));dialog.append(list);}else dialog.append(element('p','目前沒有決策衝突'));
  dialog.append(element('h3',`仍未確認：${pendingScreens.length+pendingComponents.length} 個`));const pending=element('ul',undefined,'pre-export-undecided');for(const node of pendingScreens.slice(0,5))pending.append(element('li',`畫面：${node.name}`));for(const key of pendingComponents.slice(0,Math.max(0,5-pendingScreens.length)))pending.append(element('li',`按鈕：${index.nodes.get(key.componentId)?.name||'可操作項目'}（${index.nodes.get(key.screenId)?.name||'畫面'}）`));if(pending.children.length)dialog.append(pending);else if(pendingScreens.length+pendingComponents.length>5)dialog.append(element('p','其餘項目請在確認儀表板查看'));
  dialog.append(element('p','暫存提醒：標記只存在這個瀏覽器；換電腦、換檔案位置或清除瀏覽器資料時可能無法取回，請匯出 md 保存。','storage-reminder'));
  const actions=element('div',undefined,'pre-export-actions'),proceed=element('button','仍要匯出'),back=element('button','回去處理','secondary'),skip=element('button','不再顯示','secondary');proceed.className='primary';proceed.onclick=()=>{dialog.close();void exportNow();};back.onclick=()=>dialog.close();skip.onclick=()=>{try{window.localStorage.setItem('screentrace:confirmation-preferences:v1',JSON.stringify({...preferences(),skipExportCheck:true}));}catch{}dialog.close();void exportNow();};actions.append(proceed,back,skip);dialog.append(actions);dialog.showModal();};
 exportButton.onclick=()=>{if(preferences().skipExportCheck)void exportNow();else showExportCheck();};
 let revision=0;input.onchange=async()=>{const file=input.files?.[0];if(!file)return;const token=++revision;section.setAttribute('aria-busy','true');try{if(file.size>67_108_864)throw Error(text.importSize);const imported=await importMarkdown(await file.text(),payload);if(token!==revision)return;apply(imported.state);orphans.replaceChildren();if(imported.orphans.length){orphans.append(element('h3',text.orphans));for(const orphan of imported.orphans)orphans.append(element('p',`${orphan.screenId}${orphan.componentId?' / '+orphan.componentId:''}`));}status.textContent=imported.changed?`${text.importComplete}；${text.analysisChanged}`:text.importComplete;}catch(error){if(token===revision)status.textContent=`${text.importFailed}：${String(error)}`;}finally{if(token===revision){section.removeAttribute('aria-busy');input.value='';}}};return section;
}
