import {element} from './text';import {Payload} from './contracts';import {Index} from './map';import {partitionNavigation} from './overview';import {PrototypeHistory} from './prototype-history';
export interface PrototypeOptions {back:()=>void;focus:(id:string)=>void;flow:()=>void;move:(delta:number)=>void;reset:()=>void;scroll:number}
export function transition(thumbnail:string|undefined,name:string,from:DOMRect,to:DOMRect,complete:()=>void){
 if(matchMedia('(prefers-reduced-motion: reduce)').matches){complete();return;}
 const ghost=element('div',undefined,'prototype-transition');ghost.setAttribute('aria-hidden','true');if(thumbnail?.startsWith('data:image/')){const img=element('img');img.src=thumbnail;img.alt='';ghost.append(img);}else ghost.append(element('span',name));
 ghost.style.cssText=`position:fixed;left:${to.x}px;top:${to.y}px;width:${to.width}px;height:${to.height}px;z-index:10;pointer-events:none;transform-origin:0 0;`;
 document.body.append(ghost);const animation=ghost.animate([{transform:`translate(${from.x-to.x}px,${from.y-to.y}px) scale(${from.width/to.width},${from.height/to.height})`},{transform:'none'}],{duration:300,easing:'cubic-bezier(.2,.8,.2,1)'});animation.finished.catch(()=>{}).finally(()=>{ghost.remove();complete();});
}
export function prototypeViewer(index:Index,payload:Payload,id:string,preview:HTMLElement,frame:HTMLIFrameElement,history:PrototypeHistory,options:PrototypeOptions):HTMLElement {
 const screen=index.nodes.get(id)!,metadata=payload.preview.screens?.find(s=>s.graphScreenId===id),root=element('section',undefined,'prototype-viewer'),toolbar=element('div',undefined,'prototype-toolbar'),scroller=element('div',undefined,'prototype-scroll'),stage=element('div',undefined,'prototype-stage'),status=element('div',undefined,'prototype-status');status.setAttribute('role','status');
 const back=element('button','返回總覽'),previous=element('button','上一頁'),next=element('button','下一頁'),flow=element('button','流程視圖'),reset=element('button','重置'),url=element('span',index.routes.get(id)?.[0]||'沒有已知 URL','prototype-url'),zoom=element('select');url.setAttribute('aria-label','主要 URL');url.title=url.textContent!;zoom.setAttribute('aria-label','原型縮放');
 for(const [value,label]of [['fit','適合寬度'],['.5','50%'],['.75','75%'],['1','100%']]){const option=element('option',label);option.value=value;zoom.append(option);}
 back.onclick=options.back;previous.disabled=!history.canBack;next.disabled=!history.canForward;previous.onclick=()=>options.move(-1);next.onclick=()=>options.move(1);flow.onclick=options.flow;reset.onclick=options.reset;toolbar.append(back,previous,next,url,zoom,flow,reset);
 const crumb=element('div',undefined,'focus-breadcrumb');crumb.append(element('h2',screen.name));root.append(crumb,toolbar,status,scroller);
 const width=Math.max(1,metadata?.width||1440);let height=Math.max(1,metadata?.height||900);frame.style.width=`${width}px`;frame.style.height=`${height}px`;frame.style.maxWidth='none';frame.scrolling='no';preview.style.width=`${width}px`;preview.style.height=`${height}px`;preview.style.transformOrigin='0 0';stage.append(preview);scroller.append(stage);
 const resize=()=>{if(!root.isConnected){observer.disconnect();contentObserver?.disconnect();return;}const scale=zoom.value==='fit'?Math.min(1,Math.max(1,scroller.clientWidth-16)/width):Number(zoom.value);preview.style.transform=`scale(${scale})`;preview.style.height=`${height}px`;frame.style.height=`${height}px`;stage.style.width=`${width*scale}px`;stage.style.height=`${height*scale}px`;root.dataset.scale=String(scale);};
 const observer=new ResizeObserver(resize);let contentObserver:ResizeObserver|undefined;observer.observe(scroller);zoom.onchange=resize;
 frame.addEventListener('load',()=>{if(!frame.getAttribute('srcdoc')||!frame.contentDocument)return;const doc=frame.contentDocument;const measure=()=>{height=Math.max(metadata?.height||900,doc.documentElement.scrollHeight,doc.body?.scrollHeight||0);resize();};measure();contentObserver=new ResizeObserver(measure);if(doc.body)contentObserver.observe(doc.body);scroller.scrollTop=options.scroll;root.dataset.loaded='true';});
 if(!payload.documents[id])status.textContent='未取得重建預覽';
 const destinations=element('details',undefined,'prototype-destinations');const summary=element('summary');summary.append(element('button','可前往的畫面'));summary.querySelector('button')!.onclick=e=>{e.preventDefault();destinations.open=!destinations.open;};destinations.append(summary);const parts=partitionNavigation(index);
 for(const [title,relations]of [['畫面流程',parts.flows],['全站導覽',parts.global]]as const){const group=element('section');group.append(element('h3',title));for(const relation of relations.filter(r=>r.from===id)){const node=index.nodes.get(relation.to);if(!node)continue;const button=element('button',undefined,'prototype-destination');button.dataset.destination=node.id;const thumb=payload.preview.screens?.find(s=>s.graphScreenId===node.id)?.thumbnail;if(thumb?.startsWith('data:image/')){const img=element('img');img.src=thumb;img.alt='';button.append(img);}button.append(element('span',node.name),element('small',index.routes.get(node.id)?.[0]||'沒有已知 URL'));button.onclick=()=>options.focus(node.id);group.append(button);}if(group.querySelector('button'))destinations.append(group);}
 if(destinations.querySelector('.prototype-destination'))root.append(destinations);requestAnimationFrame(resize);return root;
}
