import {element} from './text';
/** WebKit refuses parent-owned listeners attached inside script-disabled frames.
 * Only viewer-owned controls receive events here. The target document stays inert. */
export function needsSimulationSurface(){return /AppleWebKit/.test(navigator.userAgent)&&!/Chrome|Chromium|Edg/.test(navigator.userAgent);}
export function simulationSurface(frame:HTMLIFrameElement,select:(node:Element)=>void,click:(node:Element)=>void,submit:(form:HTMLFormElement)=>void,change:(node:Element)=>void,close:()=>void){
 const doc=frame.contentDocument!,host=frame.parentElement!,layer=element('div',undefined,'simulation-surface');layer.setAttribute('aria-label','靜態畫面操作層');host.append(layer);frame.style.pointerEvents='none';frame.tabIndex=-1;
 const proxies=new Map<Element,HTMLElement>(),forms=new Map<HTMLFormElement,HTMLFormElement>();let sequence=0;
 const proxyForm=(source:HTMLFormElement)=>{let form=forms.get(source);if(!form){form=element('form');form.id=`simulation-form-${++sequence}`;form.noValidate=true;form.onsubmit=event=>{event.preventDefault();submit(source);};layer.append(form);forms.set(source,form);}return form;};
 const place=(source:Element,proxy:HTMLElement)=>{const rect=source.getBoundingClientRect();proxy.style.left=`${rect.left}px`;proxy.style.top=`${rect.top}px`;proxy.style.width=`${rect.width}px`;proxy.style.height=`${rect.height}px`;proxy.hidden=!rect.width||!rect.height||doc.defaultView!.getComputedStyle(source).visibility==='hidden';proxy.title=source.getAttribute('title')||'';};
 const input=(source:HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement)=>{const proxy=element(source.localName as 'input') as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement;for(const key of ['type','name','required','pattern','min','max','step','minlength','maxlength','multiple','readonly','disabled','placeholder'])if(source.hasAttribute(key))proxy.setAttribute(key,source.getAttribute(key)!);if(source.localName==='select')for(const option of (source as HTMLSelectElement).options){const item=element('option',option.text);item.value=option.value;item.disabled=option.disabled;item.selected=option.selected;(proxy as HTMLSelectElement).append(item);}proxy.value=source.value;if(source.localName==='input')(proxy as HTMLInputElement).checked=(source as HTMLInputElement).checked;
  const computed=doc.defaultView!.getComputedStyle(source);for(const key of ['font','color','background-color','border','border-radius','padding','text-align','box-sizing','appearance'])proxy.style.setProperty(key,computed.getPropertyValue(key));proxy.style.margin='0';if(source.form)proxy.setAttribute('form',proxyForm(source.form).id);const sync=()=>{source.value=proxy.value;if(source.localName==='input')(source as HTMLInputElement).checked=(proxy as HTMLInputElement).checked;};proxy.oninput=sync;proxy.onchange=()=>{sync();if(source.localName==='select')Array.from((source as HTMLSelectElement).options).forEach((option,i)=>option.selected=(proxy as HTMLSelectElement).options[i].selected);change(source);};proxy.onclick=event=>{event.stopPropagation();select(source);click(source);};source.tabIndex=-1;return proxy;
 };
 const update=()=>{if(!host.isConnected){observer.disconnect();layer.remove();return;}for(const [source,proxy]of proxies)if(!source.isConnected){proxy.remove();proxies.delete(source);}const modal=doc.querySelector<HTMLElement>('.simulation-backdrop');layer.classList.toggle('has-modal',!!modal);
  for(const source of doc.querySelectorAll<HTMLElement>('a,button,input,select,textarea')){if(modal&&!modal.contains(source))continue;let proxy=proxies.get(source);if(!proxy){const editable=['input','select','textarea'].includes(source.localName)&&!['submit','image','button','reset','hidden','file'].includes(source.getAttribute('type')||'');if(editable)proxy=input(source as HTMLInputElement);else{proxy=element('button');(proxy as HTMLButtonElement).type='button';(proxy as HTMLButtonElement).disabled=source.hasAttribute('disabled');proxy.classList.add('simulation-hotspot');proxy.setAttribute('aria-label',source.textContent||source.getAttribute('value')||source.getAttribute('aria-label')||'操作');proxy.onclick=event=>{event.preventDefault();event.stopPropagation();if(source.closest('[data-st-simulation-ui]')){if(source.closest('.simulation-modal')&&source===source.closest('.simulation-modal')?.querySelector('button'))close();else select(source);return;}select(source);click(source);};source.tabIndex=-1;}proxy.dataset.sourceId=source.id;proxy.classList.add('simulation-proxy');layer.append(proxy);proxies.set(source,proxy);}place(source,proxy);proxy.style.pointerEvents=modal&&!modal.contains(source)?'none':'auto';}
  for(const [source,proxy]of proxies)if(modal&&!modal.contains(source))proxy.style.pointerEvents='none';
 };
 layer.onclick=event=>{const rect=layer.getBoundingClientRect(),scale=rect.width/frame.offsetWidth,node=doc.elementFromPoint((event.clientX-rect.left)/scale,(event.clientY-rect.top)/scale);if(node?.classList.contains('simulation-backdrop'))close();else if(node)select(node);};
 const observer=new ResizeObserver(update);if(doc.body)observer.observe(doc.body);observer.observe(frame);update();
 return{update,focusDialog:()=>{const source=doc.querySelector('.simulation-modal button');if(source)proxies.get(source)?.focus();},reportValidity:(form:HTMLFormElement)=>{const proxy=forms.get(form);if(proxy){for(const control of Array.from(form.elements)){const own=proxies.get(control) as HTMLInputElement|undefined;if(own&&'value'in control){own.value=(control as HTMLInputElement).value;if('checked'in control)own.checked=(control as HTMLInputElement).checked;}}proxy.reportValidity();}else form.reportValidity();}};
}
