package io.screentrace.parser.jsp;
import io.screentrace.core.*;
import io.screentrace.core.ApplicationGraph.*;
import io.screentrace.scanner.ProjectScanner.ProjectInventory;
import io.screentrace.scanner.SafeProjectFiles;
import com.fasterxml.jackson.databind.*;
import java.util.*;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.XMLConstants;
import org.xml.sax.InputSource;
import java.io.StringReader;

/** Correlates inert frontend requests with every statically compatible backend endpoint. */
public final class UrlGraphContribution {
 private static final ObjectMapper JSON=new ObjectMapper();
 private UrlGraphContribution() { }
 public static ApplicationGraph enrich(ApplicationGraph graph,ProjectInventory inventory) {
  Map<String,GraphNode> nodes=new TreeMap<>();graph.nodes().forEach(n->nodes.put(n.id(),n));Map<String,Relationship> edges=new TreeMap<>();graph.relationships().forEach(e->edges.put(e.id(),e));Map<String,Behavior> behaviors=new TreeMap<>();graph.behaviors().forEach(b->behaviors.put(b.id(),b));List<Diagnostic> diagnostics=new ArrayList<>(graph.diagnostics());
  var context=UrlResolution.context(inventory,List.of());var extensions=extensions(inventory,diagnostics);
  for(var node:graph.nodes())if(node.type()==NodeType.COMPONENT&&"FORM".equals(node.attributes().get("kind"))&&behaviors.values().stream().noneMatch(b->b.triggerId().equals(node.id())&&b.type()==BehaviorType.SUBMIT_FORM)){
   String raw=node.attributes().getOrDefault("target",node.attributes().get("action"));if(raw!=null&&!raw.startsWith("javascript:")){String id=StableGraphIds.behavior(node.id(),"submit",BehaviorType.SUBMIT_FORM,raw,0);behaviors.put(id,new Behavior(id,node.id(),"submit",BehaviorType.SUBMIT_FORM,null,node.attributes().get("guard"),null,raw,node.evidence()));}
  }
  var endpoints=nodes.values().stream().filter(n->n.type()==NodeType.ENDPOINT&&!"javascript-request".equals(n.attributes().get("origin"))).map(n->new UrlResolution.Endpoint(n.id(),n.attributes().getOrDefault("path",""),n.attributes().getOrDefault("httpMethod","ANY"),n.evidence())).toList();
  for(var b:new ArrayList<>(behaviors.values())){
   if(!Set.of(BehaviorType.CALL_API,BehaviorType.SUBMIT_FORM).contains(b.type()))continue;var trigger=nodes.get(b.triggerId());if(trigger==null)continue;
   String raw=null,method=null;boolean dynamicMethod=false;SourceLocation source=b.evidence().isEmpty()?trigger.source():b.evidence().get(0).source();
   if(b.type()==BehaviorType.CALL_API){for(var e:b.evidence())try{var item=JSON.readTree(Objects.toString(e.detail(),""));if(item!=null&&item.has("url")){raw=item.path("url").isNull()?null:item.path("url").asText();method=item.path("method").isNull()?null:item.path("method").asText();dynamicMethod=method==null;source=e.source();break;}}catch(Exception ignored){}if(raw==null&&b.targetId()!=null){var target=nodes.get(b.targetId());if(target!=null&&"javascript-request".equals(target.attributes().get("origin"))){raw=target.attributes().get("path");method=target.attributes().get("httpMethod");}}}
   else {raw=trigger.attributes().getOrDefault("target",trigger.attributes().getOrDefault("action",b.expression()));method=trigger.attributes().getOrDefault("httpMethod",trigger.attributes().getOrDefault("method","GET")).toUpperCase(Locale.ROOT);}
   boolean proven=raw!=null&&(raw.startsWith("{pageContext.request.contextPath}")||raw.startsWith("{pageContext.servletContext.contextPath}")||raw.startsWith("${pageContext.request.contextPath}")||raw.startsWith("${pageContext.servletContext.contextPath}"));
   UrlResolution.Result result;
   if("<current-view>".equals(raw)){Set<String> owners=new TreeSet<>();graph.relationships().stream().filter(e->e.type()==EdgeType.CONTAINS&&e.to().equals(b.triggerId())).forEach(e->owners.add(e.from()));Set<String> handlers=new TreeSet<>();graph.relationships().stream().filter(e->e.type()==EdgeType.RENDERS&&owners.contains(e.to())).forEach(e->handlers.add(e.from()));var current=endpoints.stream().filter(n->graph.relationships().stream().anyMatch(e->e.type()==EdgeType.HANDLED_BY&&e.from().equals(n.id())&&handlers.contains(e.to()))).toList();List<String> candidates=new ArrayList<>();for(var endpoint:current)if(UrlResolution.resolve(endpoint.path(),method,context,List.of(endpoint),false).candidates().contains(endpoint.id()))candidates.add(endpoint.id());var proof=UrlResolution.resolve(null,method,context,List.of(),false).evidence();result=new UrlResolution.Result(candidates.isEmpty()?Confidence.UNRESOLVED:candidates.size()>1?Confidence.AMBIGUOUS:Confidence.INFERRED,candidates.stream().sorted().toList(),List.of(),List.of(),proof);}
   else result=UrlResolution.resolve(raw,dynamicMethod?"UNKNOWN":method,context,endpoints,extensions,proven);
   List<AnalysisEvidence> proof=new ArrayList<>(b.evidence());proof.addAll(result.evidence());proof.add(new AnalysisEvidence(source,"UrlResolution",result.confidence().resolutionStatus(),"原始 URL="+Objects.toString(raw,"UNRESOLVED")+"；方法="+Objects.toString(method,"GET")+"；正規化="+result.paths()+"；候選="+result.candidates()));
   for(String code:result.diagnostics())diagnostics.add(new Diagnostic("URL 靜態對應："+code,Confidence.UNRESOLVED,source,code,List.of(new AnalysisEvidence(source,"UrlResolution",ResolutionStatus.UNRESOLVED,"原始 URL="+Objects.toString(raw,"UNRESOLVED")))));
   // Rebuild only request edges; unmatched frontend descriptions still retain their caller.
   final String previous=b.targetId(),requestUrl=raw,requestMethod=method;edges.entrySet().removeIf(entry->{var edge=entry.getValue();return edge.from().equals(b.triggerId())&&Set.of(EdgeType.CALLS,EdgeType.TRIGGERS).contains(edge.type())&&(result.candidates().contains(edge.to())||Objects.equals(previous,edge.to())||!result.candidates().isEmpty()&&frontendRequest(nodes.get(edge.to()),requestUrl,requestMethod));});
   String target=result.candidates().size()==1?result.candidates().get(0):result.candidates().isEmpty()&&b.type()==BehaviorType.CALL_API?previous:null;
   behaviors.put(b.id(),new Behavior(b.id(),b.triggerId(),b.event(),b.type(),target,b.guard(),b.parentId(),b.expression(),proof.stream().distinct().sorted().toList()));
   var destinations=result.candidates().isEmpty()&&target!=null?List.of(target):result.candidates();for(String destination:destinations){EdgeType type=trigger.type()==NodeType.SCREEN?EdgeType.CALLS:EdgeType.TRIGGERS;String id=ApplicationGraph.id(NodeType.COMPONENT,type+":"+b.triggerId()+":"+destination);var old=edges.get(id);List<AnalysisEvidence> combined=new ArrayList<>(proof);if(old!=null)combined.addAll(old.evidence());Confidence confidence=result.confidence();var endpoint=nodes.get(destination);if(confidence==Confidence.CONFIRMED&&endpoint!=null&&endpoint.confidence()!=Confidence.CONFIRMED)confidence=endpoint.confidence();edges.put(id,new Relationship(id,type,b.triggerId(),destination,confidence,source,combined.stream().distinct().sorted().toList()));}
  }
  nodes.entrySet().removeIf(entry->"javascript-request".equals(entry.getValue().attributes().get("origin"))&&behaviors.values().stream().noneMatch(b->entry.getKey().equals(b.targetId()))&&edges.values().stream().noneMatch(e->entry.getKey().equals(e.to())));
  return hidePrivateLocations(new ApplicationGraph(graph.application(),List.copyOf(nodes.values()),List.copyOf(edges.values()),diagnostics.stream().distinct().toList(),graph.apiContracts(),graph.schemaVersion(),List.copyOf(behaviors.values()),graph.validationRules()));
 }
 private static boolean frontendRequest(GraphNode node,String url,String method){return node!=null&&"javascript-request".equals(node.attributes().get("origin"))&&Objects.equals(url,node.attributes().get("path"))&&Objects.equals(method,node.attributes().get("httpMethod"));}
 public static ApplicationGraph hidePrivateLocations(ApplicationGraph graph){String home=System.getProperty("user.home","");if(home.length()<2)return graph;try{return JSON.treeToValue(redact(JSON.valueToTree(graph),home),ApplicationGraph.class);}catch(Exception error){throw new IllegalStateException("圖隱私處理失敗",error);}}
 private static JsonNode redact(JsonNode node,String home){if(node.isTextual())return com.fasterxml.jackson.databind.node.TextNode.valueOf(node.asText().replace(home,"[home]").replace(home.replace('\\','/'),"[home]"));if(node.isArray()){var array=JSON.createArrayNode();node.forEach(n->array.add(redact(n,home)));return array;}if(node.isObject()){var object=JSON.createObjectNode();node.fields().forEachRemaining(e->object.set(e.getKey().replace(home,"[home]"),redact(e.getValue(),home)));return object;}return node;}
 private static List<String> extensions(ProjectInventory inventory,List<Diagnostic> diagnostics){Set<String> result=new TreeSet<>();for(var file:inventory.files())if(file.getFileName().toString().equals("web.xml"))try{var factory=DocumentBuilderFactory.newInstance();factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING,true);factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD,"");factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA,"");factory.setExpandEntityReferences(false);var document=factory.newDocumentBuilder().parse(new InputSource(new StringReader(SafeProjectFiles.readUtf8Limited(inventory.root(),file,SafeProjectFiles.MAX_XML_FILE_BYTES))));var mappings=document.getElementsByTagName("servlet-mapping");for(int i=0;i<mappings.getLength();i++){var patterns=((org.w3c.dom.Element)mappings.item(i)).getElementsByTagName("url-pattern");for(int j=0;j<patterns.getLength();j++){String value=patterns.item(j).getTextContent().strip();if(value.startsWith("*."))result.add(value);}}}catch(Exception error){var source=new SourceLocation(inventory.root().relativize(file).toString().replace('\\','/'),1);diagnostics.add(new Diagnostic("Servlet 映射無法安全解析",Confidence.UNRESOLVED,source,"URL_MAPPING_UNRESOLVED",List.of(new AnalysisEvidence(source,"UrlResolution",ResolutionStatus.UNRESOLVED,"Servlet 映射無法安全解析"))));}return List.copyOf(result);}
}
