import {Graph,Evidence,Source,requireGraph} from '../contracts';
const status=new Set(['CONFIRMED','INFERRED','AMBIGUOUS','UNRESOLVED']);
const kinds=new Set('BUTTON LINK SUBMIT TEXT_INPUT TEXTAREA SELECT CHECKBOX RADIO DATE_PICKER FILE_INPUT MULTI_SELECT FORM MODAL TABLE OTHER'.split(' '));
const types=new Set('SCREEN ENTRY_POINT HANDLER VIEW COMPONENT ENDPOINT SOURCE_ARTIFACT FORM_MODEL TEMPLATE_FRAGMENT INTEGRATION'.split(' '));
export function validSource(s:Source|undefined):boolean {if(!s||!Number.isInteger(s.line)||s.line<1||!s.file||s.file.includes('..'))return false;return s.file.startsWith('workspace:')?/^workspace:[^/\\:]+$/.test(s.file):!/^[/\\~]|:/.test(s.file);}
/** Browser/Node consumer gate mirrors the canonical Java integrity constraints. */
export function strictGraph(graph:Graph):Graph {
 requireGraph(graph);const fail=(m:string):never=>{throw Error(`schema 2.2 嚴格驗證：${m}`);};
 const evidence=(items:unknown,owner:string)=>{if(!Array.isArray(items)||!items.length)fail(`缺少證據 ${owner}`);for(const e of items as Evidence[])if(!validSource(e.source)||!e.parser?.trim()||['LEGACY','UNKNOWN'].includes(e.parser)||!status.has(e.resolution))fail(`無效證據 ${owner}`);};
 const nodes=new Map(graph.nodes.map(n=>[n.id,n])),ids=new Set<string>(),routes=new Set<string>();
 const unique=(id:string)=>{if(!id?.trim()||ids.has(id))fail('重複或缺少 ID');ids.add(id);};
 for(const n of graph.nodes){unique(n.id);if(!types.has(n.type)||!status.has(n.confidence)||!n.attributes)fail(`無效節點 ${n.id}`);evidence(n.evidence,n.id);if(n.source&&!validSource(n.source))fail('來源路徑');if(n.type==='COMPONENT'&&!kinds.has(n.attributes.kind))fail('元件種類');if(n.type==='SCREEN'&&n.attributes.route){if(routes.has(n.attributes.route))fail('重複路由');routes.add(n.attributes.route);}}
 const allowed:Record<string,[string[],string[]]>={CONTAINS:[['SCREEN'],['COMPONENT']],HANDLED_BY:[['ENDPOINT'],['HANDLER']],RENDERS:[['HANDLER'],['SCREEN','VIEW']],NAVIGATES_TO:[['COMPONENT'],['SCREEN']],TRIGGERS:[['COMPONENT'],['ENDPOINT','ENTRY_POINT']],INCLUDES:[['SCREEN','VIEW','TEMPLATE_FRAGMENT'],['VIEW','TEMPLATE_FRAGMENT']],BINDS_TO:[['COMPONENT'],['FORM_MODEL']],FORWARDS_TO:[['HANDLER','ENDPOINT'],['SCREEN','VIEW']],CALLS:[['SCREEN','HANDLER','COMPONENT'],['ENDPOINT','INTEGRATION']]};
 const edgeIds=new Set<string>(),edges=graph.relationships||[],owned=new Set(edges.filter(e=>e.type==='CONTAINS').map(e=>e.to));
 for(const e of edges){if(!e.id||edgeIds.has(e.id))fail('重複關聯');edgeIds.add(e.id);const a=nodes.get(e.from),b=nodes.get(e.to);if(!a||!b)fail('未知關聯節點');const pair=allowed[e.type];if(pair&&(!pair[0].includes(a!.type)||!pair[1].includes(b!.type))||!pair&&!['DECLARED_BY','DEFINED_IN'].includes(e.type))fail('關聯種類');if(!status.has(e.confidence))fail('關聯信心');evidence((e as unknown as {evidence:unknown}).evidence,e.id);if(e.source&&!validSource(e.source))fail('關聯來源');if(e.type==='NAVIGATES_TO'&&(!owned.has(e.from)||e.confidence==='CONFIRMED'&&a!.attributes.target&&![b!.attributes.route,b!.attributes.view].includes(a!.attributes.target)))fail('導覽關聯');}
 const rules=new Map((graph.validationRules||[]).map(r=>[r.id,r]));for(const r of rules.values()){unique(r.id);if(!r.kind||!r.fields?.length||!['MARKUP','CLIENT','SERVER'].includes(r.layer))fail('檢核規則');evidence(r.evidence,r.id);}if(rules.size!==(graph.validationRules||[]).length)fail('重複規則');
 const bs=new Map((graph.behaviors||[]).map(b=>[b.id,b]));for(const b of graph.behaviors||[]){unique(b.id);if(!b.event||!['NAVIGATE','SUBMIT_FORM','CALL_API','OPEN_DIALOG','VALIDATE','UI_STATE_CHANGE','SELECT_CHANGE','UNKNOWN'].includes(b.type)||!b.triggerId&&!b.parentId)fail('行為');if(b.triggerId&&!['SCREEN','COMPONENT'].includes(nodes.get(b.triggerId)?.type||''))fail('觸發者');evidence(b.evidence,b.id);if(b.targetId){const target=nodes.get(b.targetId);if(b.type==='VALIDATE'?!rules.has(b.targetId):b.type==='CALL_API'||b.type==='SUBMIT_FORM'?target?.type!=='ENDPOINT':b.type==='NAVIGATE'?!['SCREEN','ENDPOINT'].includes(target?.type||''):b.type==='OPEN_DIALOG'?target?.type!=='COMPONENT'||target.attributes.kind!=='MODAL':!target&&!rules.has(b.targetId))fail('行為目標');}const seen=new Set<string>();let cursor=b;while(cursor.parentId){if(seen.has(cursor.id)||!bs.has(cursor.parentId))fail('行為父循環／未知父行為');seen.add(cursor.id);cursor=bs.get(cursor.parentId)!;}}
 const contracts=new Set<string>();for(const c of graph.apiContracts||[]){if(nodes.get(c.endpointId)?.type!=='ENDPOINT'||contracts.has(c.endpointId))fail('API 契約');contracts.add(c.endpointId);}return graph;
}
