<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.screentrace</groupId>
    <artifactId>screentrace</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>screentrace-report</artifactId>

  <dependencies>
    <dependency>
      <groupId>io.screentrace</groupId>
      <artifactId>screentrace-core</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
